'use client';

import { useEffect, useMemo, useState } from 'react';
import { supabase } from '@/lib/supabase';

type Row=Record<string,any>;
const DIAMBARS='d3136b7f-ef28-43e8-af53-30fa6de70c62';
const ELITE='5454ad8f-8f2b-4812-9923-ab7d0b1f8748';
const TEAMS=[{id:'d9bb5390-94cb-461e-b2cd-a326da2cfa3d',name:'PRO A'},{id:'44f6976d-f5ef-4dcf-980f-ce3995e99877',name:'U19 · PRO B'},{id:'28b38b9f-3de0-419d-8275-b331a074b7f4',name:'U17'},{id:'e652df98-4653-416c-b794-3763e38a629d',name:'U15'}];
type Tab='session'|'family'|'education'|'history';

export default function AdvancedAdmin(){
 const [ready,setReady]=useState(false),[ok,setOk]=useState(false),[msg,setMsg]=useState('');
 const [org,setOrg]=useState(DIAMBARS),[team,setTeam]=useState(TEAMS[2].id),[tab,setTab]=useState<Tab>('session');
 const [players,setPlayers]=useState<Row[]>([]),[playerId,setPlayerId]=useState('');
 const [guardian,setGuardian]=useState<Row>({full_name:'',relationship:'',phone:'',email:'',is_legal_representative:false,is_primary_contact:false,is_emergency_contact:false,lives_with_player:false,address:'',city:'',country:'',notes:''});
 const [education,setEducation]=useState<Row>({school_name:'',school_city:'',class_level:'',study_track:'',diploma_target:'',school_status:'',schedule_summary:'',constraints:'',school_referent_name:'',school_referent_phone:'',school_referent_email:'',academic_project:'',professional_project:'',period_start:'',period_end:'',notes:''});
 const [history,setHistory]=useState<Row>({club_name:'',country:'',city:'',competition_level:'',category:'',season:'',age_at_club:'',position:'',matches:'',starts:'',minutes_played:'',goals:'',assists:'',training_sessions_per_week:'',training_sessions_per_season:'',average_session_duration_min:'',strength_sessions_per_week:'',tournaments:'',selections:'',injuries_summary:'',start_date:'',end_date:'',notes:''});
 const [session,setSession]=useState<Row>({type:'training',title:'Entraînement collectif',session_date:new Date().toISOString().slice(0,10),planned_duration_min:75,planned_rpe:6,location:'',notes:''});
 const isD=org===DIAMBARS; const theme=isD?{bg:'#09090B',surface:'#141416',surface2:'#1B1B1F',border:'#2B2B31',text:'#FAFAFA',muted:'#92929B',accent:'#E31E24'}:{bg:'#F4F4F5',surface:'#fff',surface2:'#F7F7F8',border:'#E4E4E7',text:'#111',muted:'#71717A',accent:'#111'};
 async function load(){const {data}=await supabase.from('players').select('id,organization_id,team_id,display_name,first_name,last_name,primary_position,position').eq('active',true);setPlayers(data||[])}
 useEffect(()=>{(async()=>{const {data:{session:s}}=await supabase.auth.getSession();if(!s){setReady(true);return}const {data}=await supabase.from('profiles').select('is_super_admin').eq('user_id',s.user.id).maybeSingle();if(!data?.is_super_admin){setReady(true);return}setOk(true);await load();setReady(true)})()},[]);
 useEffect(()=>{if(!isD)setTeam('');else if(!TEAMS.some(t=>t.id===team))setTeam(TEAMS[2].id)},[org,isD,team]);
 const scoped=useMemo(()=>players.filter(p=>p.organization_id===org&&(!isD||p.team_id===team)),[players,org,team,isD]);
 useEffect(()=>{if(!scoped.some(p=>p.id===playerId))setPlayerId(scoped[0]?.id||'')},[scoped,playerId]);
 async function insert(table:string,payload:Row,success:string){if(!playerId&&table!=='sessions'){setMsg('Sélectionne un joueur.');return}setMsg('Enregistrement…');const base=table==='sessions'?{organization_id:org,team_id:isD?team:null}:{organization_id:org,player_id:playerId};const {error}=await supabase.from(table).insert({...base,...payload});setMsg(error?error.message:success)}
 async function saveSession(){const payload={type:session.type,title:session.title||null,session_date:session.session_date,planned_duration_min:num(session.planned_duration_min),planned_rpe:num(session.planned_rpe),metadata:{location:session.location||null,notes:session.notes||null,created_from:'admin'}};await insert('sessions',payload,'Séance créée ✓')}
 async function saveGuardian(){if(!guardian.full_name){setMsg('Le nom du représentant est obligatoire.');return}await insert('player_guardians',{...clean(guardian),is_legal_representative:!!guardian.is_legal_representative,is_primary_contact:!!guardian.is_primary_contact,is_emergency_contact:!!guardian.is_emergency_contact,lives_with_player:!!guardian.lives_with_player},'Famille / contact enregistré ✓')}
 async function saveEducation(){await insert('player_education',{...clean(education)},'Scolarité enregistrée ✓')}
 async function saveHistory(){if(!history.club_name){setMsg('Le nom du club est obligatoire.');return}const numeric=['age_at_club','matches','starts','minutes_played','goals','assists','training_sessions_per_week','training_sessions_per_season','average_session_duration_min','strength_sessions_per_week'];const payload=clean(history);numeric.forEach(k=>payload[k]=num(history[k]));await insert('player_club_history',payload,'Historique club enregistré ✓')}
 if(!ready)return <main style={S.center}>Chargement…</main>;if(!ok)return <main style={S.center}>Accès administrateur principal requis.</main>;
 return <main style={{minHeight:'100vh',background:theme.bg,color:theme.text,fontFamily:'Inter,system-ui,sans-serif'}}><header style={{...S.header,background:theme.surface,borderColor:theme.border}}><a href='/admin/workspace' style={{...S.link,color:theme.text,borderColor:theme.border}}>← Dashboard</a><div><b>HDY PERFORMANCE ENGINE</b><small style={{display:'block',color:theme.muted}}>Séances & dossier joueur étendu</small></div><a href='/admin/manage' style={{...S.link,color:theme.text,borderColor:theme.border}}>Saisie principale</a></header><section style={S.wrap}>
 <div style={{...S.scope,background:theme.surface,borderColor:theme.border}}><label>ORGANISATION<select value={org} onChange={e=>setOrg(e.target.value)} style={field(theme)}><option value={DIAMBARS}>DIAMBARS FC</option><option value={ELITE}>HDY ELITE</option></select></label>{isD&&<label>ÉQUIPE<select value={team} onChange={e=>setTeam(e.target.value)} style={field(theme)}>{TEAMS.map(t=><option value={t.id} key={t.id}>{t.name}</option>)}</select></label>}<label>JOUEUR<select value={playerId} onChange={e=>setPlayerId(e.target.value)} style={field(theme)}><option value=''>— sélectionner —</option>{scoped.map(p=><option value={p.id} key={p.id}>{p.display_name||`${p.first_name} ${p.last_name}`} · {p.primary_position||p.position||'—'}</option>)}</select></label></div>
 <nav style={{...S.tabs,background:theme.surface,borderColor:theme.border}}>{([['session','Créer une séance'],['family','Famille & urgence'],['education','Scolarité'],['history','Historique clubs']] as [Tab,string][]).map(([id,l])=><button key={id} onClick={()=>setTab(id)} style={tabStyle(tab===id,theme)}>{l}</button>)}</nav>{msg&&<div style={{...S.notice,background:theme.surface,borderColor:theme.border}}>{msg}</div>}
 {tab==='session'&&<Card title='Nouvelle séance staff' theme={theme}><div style={S.formGrid}><Edit label='Type' k='type' data={session} setData={setSession} theme={theme}/><Edit label='Titre' k='title' data={session} setData={setSession} theme={theme}/><Edit label='Date' k='session_date' type='date' data={session} setData={setSession} theme={theme}/><Edit label='Durée prévue (min)' k='planned_duration_min' type='number' data={session} setData={setSession} theme={theme}/><Edit label='RPE prévu' k='planned_rpe' type='number' data={session} setData={setSession} theme={theme}/><Edit label='Lieu' k='location' data={session} setData={setSession} theme={theme}/><Edit label='Notes' k='notes' data={session} setData={setSession} theme={theme}/></div><button onClick={saveSession} style={{...S.primary,background:theme.accent}}>Créer la séance</button><p style={{color:theme.muted}}>La séance créée sera ensuite utilisée pour rattacher le RPE Foster au bon jour, à la bonne organisation et à la bonne équipe.</p></Card>}
 {tab==='family'&&<Card title='Famille, représentant légal & urgence' theme={theme}><div style={S.formGrid}><Edit label='Nom complet *' k='full_name' data={guardian} setData={setGuardian} theme={theme}/><Edit label='Lien avec le joueur' k='relationship' data={guardian} setData={setGuardian} theme={theme}/><Edit label='Téléphone' k='phone' data={guardian} setData={setGuardian} theme={theme}/><Edit label='Email' k='email' type='email' data={guardian} setData={setGuardian} theme={theme}/><Edit label='Adresse' k='address' data={guardian} setData={setGuardian} theme={theme}/><Edit label='Ville' k='city' data={guardian} setData={setGuardian} theme={theme}/><Edit label='Pays' k='country' data={guardian} setData={setGuardian} theme={theme}/><Edit label='Notes' k='notes' data={guardian} setData={setGuardian} theme={theme}/></div><div style={S.checks}>{[['is_legal_representative','Représentant légal'],['is_primary_contact','Contact principal'],['is_emergency_contact','Contact urgence'],['lives_with_player','Vit avec le joueur']].map(([k,l])=><label key={k}><input type='checkbox' checked={!!guardian[k]} onChange={e=>setGuardian({...guardian,[k]:e.target.checked})}/>{l}</label>)}</div><button onClick={saveGuardian} style={{...S.primary,background:theme.accent}}>Enregistrer le contact</button></Card>}
 {tab==='education'&&<Card title='Scolarité & projet académique' theme={theme}><div style={S.formGrid}>{EDU_FIELDS.map(([k,l,t])=><Edit key={k} label={l} k={k} type={t} data={education} setData={setEducation} theme={theme}/>)}</div><button onClick={saveEducation} style={{...S.primary,background:theme.accent}}>Enregistrer la scolarité</button></Card>}
 {tab==='history'&&<Card title='Historique clubs & volume sportif antérieur' theme={theme}><div style={S.formGrid}>{HIST_FIELDS.map(([k,l,t])=><Edit key={k} label={l} k={k} type={t} data={history} setData={setHistory} theme={theme}/>)}</div><button onClick={saveHistory} style={{...S.primary,background:theme.accent}}>Ajouter le club à l’historique</button></Card>}
 </section></main>
}

const EDU_FIELDS:[string,string,string][]=[['school_name','Établissement','text'],['school_city','Ville établissement','text'],['class_level','Niveau / classe','text'],['study_track','Filière','text'],['diploma_target','Diplôme visé','text'],['school_status','Statut scolaire','text'],['schedule_summary','Emploi du temps / rythme','text'],['constraints','Contraintes scolaires','text'],['school_referent_name','Référent scolaire','text'],['school_referent_phone','Téléphone référent','text'],['school_referent_email','Email référent','email'],['academic_project','Projet académique','text'],['professional_project','Projet professionnel','text'],['period_start','Début période','date'],['period_end','Fin période','date'],['notes','Notes','text']];
const HIST_FIELDS:[string,string,string][]=[['club_name','Club *','text'],['country','Pays','text'],['city','Ville','text'],['competition_level','Niveau compétition','text'],['category','Catégorie','text'],['season','Saison','text'],['age_at_club','Âge au club','number'],['position','Poste','text'],['matches','Matchs / saison','number'],['starts','Titularisations','number'],['minutes_played','Minutes jouées','number'],['goals','Buts','number'],['assists','Passes décisives','number'],['training_sessions_per_week','Entraînements / semaine','number'],['training_sessions_per_season','Entraînements / saison','number'],['average_session_duration_min','Durée moyenne séance (min)','number'],['strength_sessions_per_week','Musculation / semaine','number'],['tournaments','Tournois','text'],['selections','Sélections','text'],['injuries_summary','Résumé blessures','text'],['start_date','Date début','date'],['end_date','Date fin','date'],['notes','Notes','text']];
function Edit({label,k,type='text',data,setData,theme}:{label:string;k:string;type?:string;data:Row;setData:(x:Row)=>void;theme:any}){return <label>{label}<input type={type} value={data[k]??''} onChange={e=>setData({...data,[k]:e.target.value})} style={field(theme)}/></label>}
function Card({title,theme,children}:{title:string;theme:any;children:React.ReactNode}){return <section style={{...S.card,background:theme.surface,borderColor:theme.border}}><h1>{title}</h1>{children}</section>}
function clean(x:Row){const out:Row={};Object.entries(x).forEach(([k,v])=>out[k]=v===''?null:v);return out}
function num(v:any){if(v===''||v===null||v===undefined)return null;const n=Number(v);return Number.isFinite(n)?n:null}
function field(t:any):React.CSSProperties{return {width:'100%',height:43,boxSizing:'border-box',marginTop:6,border:`1px solid ${t.border}`,borderRadius:10,padding:'0 10px',background:t.surface2,color:t.text}}
function tabStyle(a:boolean,t:any):React.CSSProperties{return {border:0,borderRadius:10,padding:'11px 14px',fontWeight:850,cursor:'pointer',background:a?t.accent:'transparent',color:a?'#fff':t.muted}}
const S:Record<string,React.CSSProperties>={center:{minHeight:'80vh',display:'grid',placeItems:'center'},header:{minHeight:70,borderBottom:'1px solid',padding:'10px 22px',display:'flex',gap:18,alignItems:'center',justifyContent:'space-between',position:'sticky',top:0,zIndex:20},link:{textDecoration:'none',border:'1px solid',borderRadius:10,padding:'8px 11px'},wrap:{maxWidth:1300,margin:'0 auto',padding:24},scope:{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(220px,1fr))',gap:12,border:'1px solid',borderRadius:16,padding:14},tabs:{display:'flex',gap:7,border:'1px solid',borderRadius:14,padding:7,margin:'16px 0',overflowX:'auto'},notice:{border:'1px solid',borderRadius:12,padding:12,marginBottom:14},card:{border:'1px solid',borderRadius:18,padding:18},formGrid:{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(210px,1fr))',gap:12,margin:'15px 0'},primary:{border:0,color:'#fff',borderRadius:10,padding:'12px 16px',fontWeight:850,cursor:'pointer'},checks:{display:'flex',gap:16,flexWrap:'wrap',margin:'12px 0 18px'}};