'use client';

import { useEffect,useMemo,useState } from 'react';
import { supabase } from '@/lib/supabase';
import TeamAvailabilityToday from '@/components/TeamAvailabilityToday';
import { reviewSignal, summarize, toNum, type SignalLevel } from '@/lib/stats';
import { useOrg } from '@/lib/org-context';
import { exportCsv, timestampedName } from '@/lib/csv-export';

type Row=Record<string,any>;
const SIGNAL_COLOR:Record<SignalLevel,string>={green:'#16A34A',orange:'#F59E0B',red:'#DC2626',gray:'#71717A'};
function playerSignal(pid:string,q:Row[],rpe:Row[],pain:Row[],gps:Row[]){
 const today=new Date().toISOString().slice(0,10);
 const qp=q.filter(x=>x.player_id===pid),rp=rpe.filter(x=>x.player_id===pid),pp=pain.filter(x=>x.player_id===pid),gp=gps.filter(x=>x.player_id===pid);
 const hSum=summarize(qp.map(x=>({date:String(x.submitted_at??''),value:toNum(x.answers?.hooper_total)})));
 const sSum=summarize(rp.map(x=>({date:String(x.submitted_at??''),value:toNum(x.load_ua)??((toNum(x.rpe)??0)*(toNum(x.actual_duration_min)??0)||null)})));
 const recentPain=pp.filter(x=>{const t=new Date(x.declared_at||x.created_at||'').getTime();return Number.isFinite(t)&&t>=Date.now()-7*86400000&&toNum(x.intensity)!==null}).map(x=>toNum(x.intensity) as number);
 const respondedToday=qp.some(x=>String(x.submitted_at??'').slice(0,10)===today)||rp.some(x=>String(x.submitted_at??'').slice(0,10)===today);
 return reviewSignal({respondedToday,hooperLast:hSum.last,hooperMean28:hSum.mean28,hooperSd28:hSum.sd28,painMax:recentPain.length?Math.max(...recentPain):null,unusualSymptom:qp[0]?.answers?.unusual_symptom===true,srpeLast:sSum.last,srpeMean7:sSum.mean7,acwr:toNum(gp[0]?.metrics?.acwr)});
}
function km(m:any,keyKm:string,keyM:string){const a=num(m?.[keyKm]);if(a!==null)return a;const b=num(m?.[keyM]);return b===null?null:b/1000}
export default function Monitoring(){
 const {environments,currentEnvId:org,setCurrentEnvId:setOrg,currentTeamId:team,setCurrentTeamId:setTeam,teamsFor,usesTeams,currentEnv}=useOrg();
 const isElite=currentEnv?.type==='elite_performance';
 const scopeTeam=usesTeams(org)&&team?team:'';
 const [ready,setReady]=useState(false),[ok,setOk]=useState(false);
 const [players,setPlayers]=useState<Row[]>([]),[q,setQ]=useState<Row[]>([]),[rpe,setRpe]=useState<Row[]>([]),[pain,setPain]=useState<Row[]>([]),[hrv,setHrv]=useState<Row[]>([]),[gps,setGps]=useState<Row[]>([]),[alerts,setAlerts]=useState<Row[]>([]);
 useEffect(()=>{(async()=>{const {data:{session}}=await supabase.auth.getSession();if(!session){setReady(true);return}const [{data:p},{data:m}]=await Promise.all([supabase.from('profiles').select('is_super_admin').eq('user_id',session.user.id).maybeSingle(),supabase.from('memberships').select('id').eq('user_id',session.user.id).eq('active',true).limit(1)]);if(p?.is_super_admin||m?.length)setOk(true);setReady(true)})()},[]);
 useEffect(()=>{if(ok&&org)load()},[ok,org,scopeTeam]);
 async function load(){let base=supabase.from('players').select('id,display_name,first_name,last_name,primary_position,position').eq('organization_id',org).eq('active',true);if(scopeTeam)base=base.eq('team_id',scopeTeam);const {data:p}=await base;setPlayers((p||[]) as Row[]);const ids=(p||[]).map(x=>x.id);if(!ids.length){setQ([]);setRpe([]);setPain([]);setHrv([]);setGps([]);setAlerts([]);return}const req:any[]=[supabase.from('questionnaire_responses').select('player_id,answers,submitted_at').eq('organization_id',org).in('player_id',ids).order('submitted_at',{ascending:false}).limit(1000),supabase.from('session_rpe').select('player_id,rpe,load_ua,actual_duration_min,submitted_at').eq('organization_id',org).in('player_id',ids).order('submitted_at',{ascending:false}).limit(1000),supabase.from('pain_declarations').select('*').eq('organization_id',org).in('player_id',ids).order('declared_at',{ascending:false}).limit(1000),supabase.from('gps_records').select('player_id,metrics,provider,source,recorded_at').eq('organization_id',org).in('player_id',ids).order('recorded_at',{ascending:false}).limit(1500),supabase.from('alerts').select('id,player_id,level,reason,status,related_data,created_at').eq('organization_id',org).in('player_id',ids).neq('status','closed').order('created_at',{ascending:false}).limit(500)];if(isElite)req.push(supabase.from('hrv_records').select('player_id,measurement_date,rmssd_ms,ln_rmssd,resting_hr_bpm').eq('organization_id',org).in('player_id',ids).order('measurement_date',{ascending:false}).limit(1000));const res=await Promise.all(req);setQ((res[0].data||[]) as Row[]);setRpe((res[1].data||[]) as Row[]);setPain((res[2].data||[]) as Row[]);setGps((res[3].data||[]) as Row[]);setAlerts((res[4].data||[]) as Row[]);setHrv(isElite?((res[5]?.data||[]) as Row[]):[])}
 const rows=useMemo<Row[]>(()=>players.map((p:Row)=>{const qq=q.find(x=>x.player_id===p.id),rr=rpe.find(x=>x.player_id===p.id),pp=pain.find(x=>x.player_id===p.id),gg=gps.find(x=>x.player_id===p.id),aa=alerts.find(x=>x.player_id===p.id),hh=hrv.find(x=>x.player_id===p.id);const sig=playerSignal(p.id,q,rpe,pain,gps);const a=qq?.answers||{},m=gg?.metrics||{};const hooper=a.hooper_total??sum([a.sleep_quality,a.fatigue,a.soreness,a.stress]);const symptom=a.unusual_symptom===true;const computedSrpe=(rr?.rpe||0)*(rr?.actual_duration_min||0);return {...p,hooper,symptom,rpe:rr?.rpe??null,srpe:rr?.load_ua??(computedSrpe||null),pain:pp?.intensity??pp?.pain_intensity??null,distanceKm:km(m,'total_distance_km','total_distance_m'),hsrKm:km(m,'high_intensity_distance_km','high_speed_distance_m'),sprintKm:km(m,'sprint_distance_km','sprint_distance_m'),sprints:m.sprint_count??null,vmax:m.max_speed_kmh??null,external:m.external_load??null,acwr:m.acwr??null,gpsDate:gg?.recorded_at??null,provider:gg?.provider??null,source:gg?.source??null,alert:aa??null,signal:sig,rmssd:hh?.rmssd_ms??null,lnrmssd:hh?.ln_rmssd??null,rhr:hh?.resting_hr_bpm??null} as Row}),[players,q,rpe,pain,gps,alerts,hrv]);
 function exportHooperRpe(){
  exportCsv(timestampedName(`hooper_rpe_${currentEnv?.branding?.label||currentEnv?.name||'monitoring'}`),rows,[
   {key:'name',label:'Athlète',value:x=>x.display_name||`${x.first_name} ${x.last_name}`},
   {key:'hooper',label:'Hooper /28'},{key:'symptom',label:'Symptôme inhabituel',value:x=>x.symptom?'oui':'non'},
   {key:'rpe',label:'RPE'},{key:'srpe',label:'sRPE (UA)'},{key:'pain',label:'Douleur /10'},
   {key:'signal',label:'Signal',value:x=>x.signal?.level||''},
  ]);
 }
 function exportGpsRaw(){
  exportCsv(timestampedName(`gps_brut_${currentEnv?.branding?.label||currentEnv?.name||'monitoring'}`),gps,[
   {key:'player_id',label:'Joueur',value:g=>players.find(p=>p.id===g.player_id)?.display_name||g.player_id},
   {key:'recorded_at',label:'Date'},{key:'provider',label:'Fournisseur'},{key:'source',label:'Source'},
   {key:'distance',label:'Distance km',value:g=>km(g.metrics,'total_distance_km','total_distance_m')},
   {key:'hsr',label:'HSR km',value:g=>km(g.metrics,'high_intensity_distance_km','high_speed_distance_m')},
   {key:'sprintKm',label:'Sprint km',value:g=>km(g.metrics,'sprint_distance_km','sprint_distance_m')},
   {key:'sprints',label:'Nb sprints',value:g=>g.metrics?.sprint_count??''},
   {key:'vmax',label:'Vitesse max',value:g=>g.metrics?.max_speed_kmh??''},
   {key:'acwr',label:'ACWR',value:g=>g.metrics?.acwr??''},
  ]);
 }
 if(!ready)return <main style={S.center}>Chargement…</main>;if(!ok)return <main style={S.center}>Accès staff requis.</main>;
 return <main style={S.main}><header style={S.header}><div><span style={S.kicker}>SPORT & PERFORMANCE</span><h1 style={S.h1}>Monitoring journalier</h1><p style={S.sub}>Hooper · RPE Foster · sRPE · douleur · GPS · ACWR{isElite?' · HRV':''}. Les alertes automatiques déclenchent une revue staff, jamais une décision médicale autonome.</p></div><a href='/admin/sport' style={S.back}>← Sport & Performance</a></header>
 <section style={S.filters}><label>Environnement<select value={org} onChange={e=>setOrg(e.target.value)} style={S.input}>{environments.map(e=><option key={e.id} value={e.id}>{e.branding?.label||e.name}</option>)}</select></label>{usesTeams(org)&&<label>Équipe<select value={team} onChange={e=>setTeam(e.target.value)} style={S.input}><option value=''>Toutes les équipes</option>{teamsFor(org).map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label>}{usesTeams(org)&&<><a href='/admin/sport/gps' style={S.hrv}>Importer GPS →</a><a href='/admin/sport/alerts' style={S.alertLink}>Alertes →</a></>}{isElite&&<a href='/admin/sport/hrv' style={S.hrv}>Importer / analyser HRV →</a>}<button onClick={exportHooperRpe} style={S.exportBtn}>Export CSV Hooper/RPE</button><button onClick={exportGpsRaw} style={S.exportBtn}>Export CSV GPS brut</button></section>
 <TeamAvailabilityToday organizationId={org} teamId={scopeTeam||null}/>
 <section style={S.card}><div style={S.tableWrap}><table style={S.table}><thead><tr><th>Athlète</th><th>Statut</th><th>Alerte</th><th>Hooper /28</th><th>RPE</th><th>sRPE</th><th>Douleur</th><th>Dist. km</th><th>HID/HSR km</th><th>Sprint km</th><th>Sprints</th><th>Vmax</th><th>Ext. load</th><th>ACWR</th>{isElite&&<><th>RMSSD</th><th>LnRMSSD</th><th>FC repos</th></>}</tr></thead><tbody>{rows.map((x:Row)=><tr key={x.id}><td><a href={`/admin/sport/players/${x.id}`} style={S.playerLink}><b>{x.display_name||`${x.first_name} ${x.last_name}`}</b><small>{x.primary_position||x.position||'—'}{x.gpsDate?` · GPS ${new Date(x.gpsDate).toLocaleDateString('fr-FR')}`:''}</small></a></td><td title={(x.signal?.reasons||[]).join(' · ')}><span style={{display:'inline-block',width:11,height:11,borderRadius:999,background:SIGNAL_COLOR[(x.signal?.level||'gray') as SignalLevel]}}/></td><td>{x.alert?<a href='/admin/sport/alerts' title={x.alert.reason} style={{...S.badge,background:x.alert.level==='red'?'#7F1D1D':'#713F12'}}>{x.alert.level==='red'?'ALERTE':'VIGILANCE'}</a>:'—'}</td><td>{show(x.hooper)}{x.symptom&&<b title='Symptôme inhabituel déclaré' style={{marginLeft:6,color:'#DC2626'}}>⚠︎</b>}</td><td>{show(x.rpe)}</td><td>{show(x.srpe)}</td><td>{show(x.pain)}</td><td>{show(x.distanceKm)}</td><td>{show(x.hsrKm)}</td><td>{show(x.sprintKm)}</td><td>{show(x.sprints)}</td><td>{show(x.vmax)}</td><td>{show(x.external)}</td><td>{show(x.acwr)}</td>{isElite&&<><td>{show(x.rmssd)}</td><td>{show(x.lnrmssd)}</td><td>{show(x.rhr)}</td></>}</tr>)}</tbody></table></div>{!rows.length&&<p style={S.sub}>Aucun athlète dans ce périmètre.</p>}</section></main>
}
function num(v:any){const n=Number(v);return Number.isFinite(n)?n:null}function sum(v:any[]){const a=v.map(num);return a.every(x=>x!==null)?a.reduce((s,x)=>s+(x||0),0):null}function show(v:any){return v===null||v===undefined||v===''?'—':String(typeof v==='number'?Math.round(v*100)/100:v)}
const S:Record<string,React.CSSProperties>={center:{minHeight:'80vh',display:'grid',placeItems:'center',fontFamily:'system-ui'},main:{minHeight:'100vh',background:'#09090B',color:'#FAFAFA',fontFamily:'Inter,system-ui,sans-serif',padding:28},header:{maxWidth:1280,margin:'0 auto 18px',display:'flex',justifyContent:'space-between',gap:20},kicker:{fontSize:11,fontWeight:900,letterSpacing:1.5,color:'#E31E24'},h1:{fontSize:'clamp(38px,5vw,64px)',margin:'4px 0',letterSpacing:-2.5},sub:{color:'#A1A1AA'},back:{color:'#fff',textDecoration:'none',border:'1px solid #2B2B31',borderRadius:10,padding:'10px 12px',height:'fit-content'},filters:{maxWidth:1280,margin:'0 auto 14px',display:'flex',gap:12,alignItems:'end',flexWrap:'wrap',background:'#141416',border:'1px solid #2B2B31',borderRadius:16,padding:14},input:{display:'block',minWidth:220,height:42,marginTop:6,background:'#1B1B1F',color:'#fff',border:'1px solid #34343A',borderRadius:10,padding:'0 10px'},hrv:{marginLeft:'auto',background:'#fff',color:'#111',textDecoration:'none',padding:'12px 14px',borderRadius:10,fontWeight:850},alertLink:{background:'#E31E24',color:'#fff',textDecoration:'none',padding:'12px 14px',borderRadius:10,fontWeight:850},card:{maxWidth:1280,margin:'0 auto',background:'#141416',border:'1px solid #2B2B31',borderRadius:18,padding:16},tableWrap:{overflowX:'auto'},table:{width:'100%',borderCollapse:'collapse',fontSize:13},playerLink:{color:'#fff',textDecoration:'none',display:'grid',gap:3},badge:{display:'inline-block',color:'#fff',textDecoration:'none',padding:'5px 8px',borderRadius:999,fontSize:10,fontWeight:900},exportBtn:{height:44,border:'1px solid #3F3F46',borderRadius:10,background:'#1A1A1D',color:'#fff',fontWeight:800,fontSize:12,padding:'0 12px',cursor:'pointer'}}