'use client';

import { useEffect,useMemo,useState } from 'react';
import { supabase } from '@/lib/supabase';

type Row=Record<string,any>;
const DIAMBARS='d3136b7f-ef28-43e8-af53-30fa6de70c62';
const ELITE='5454ad8f-8f2b-4812-9923-ab7d0b1f8748';
const TEAMS=[{id:'d9bb5390-94cb-461e-b2cd-a326da2cfa3d',name:'PRO A'},{id:'44f6976d-f5ef-4dcf-980f-ce3995e99877',name:'U19 · PRO B'},{id:'28b38b9f-3de0-419d-8275-b331a074b7f4',name:'U17'},{id:'e652df98-4653-416c-b794-3763e38a629d',name:'U15'}];

export default function Monitoring(){
 const [ready,setReady]=useState(false),[ok,setOk]=useState(false),[org,setOrg]=useState(DIAMBARS),[team,setTeam]=useState(TEAMS[2].id);
 const [players,setPlayers]=useState<Row[]>([]),[q,setQ]=useState<Row[]>([]),[rpe,setRpe]=useState<Row[]>([]),[pain,setPain]=useState<Row[]>([]),[hrv,setHrv]=useState<Row[]>([]);
 useEffect(()=>{(async()=>{const {data:{session}}=await supabase.auth.getSession();if(!session){setReady(true);return}const [{data:p},{data:m}]=await Promise.all([supabase.from('profiles').select('is_super_admin').eq('user_id',session.user.id).maybeSingle(),supabase.from('memberships').select('id').eq('user_id',session.user.id).eq('active',true).limit(1)]);if(p?.is_super_admin||m?.length)setOk(true);setReady(true)})()},[]);
 useEffect(()=>{if(ok)load()},[ok,org,team]);
 async function load(){const base=org===DIAMBARS?supabase.from('players').select('id,display_name,first_name,last_name,primary_position,position').eq('organization_id',org).eq('team_id',team).eq('active',true):supabase.from('players').select('id,display_name,first_name,last_name,primary_position,position').eq('organization_id',org).eq('active',true);const {data:p}=await base;setPlayers(p||[]);const ids=(p||[]).map(x=>x.id);if(!ids.length){setQ([]);setRpe([]);setPain([]);setHrv([]);return}const req:any[]=[supabase.from('questionnaire_responses').select('player_id,answers,submitted_at').eq('organization_id',org).in('player_id',ids).order('submitted_at',{ascending:false}).limit(1000),supabase.from('session_rpe').select('player_id,rpe,load_ua,actual_duration_min,submitted_at').eq('organization_id',org).in('player_id',ids).order('submitted_at',{ascending:false}).limit(1000),supabase.from('pain_declarations').select('*').eq('organization_id',org).in('player_id',ids).order('created_at',{ascending:false}).limit(1000)];if(org===ELITE)req.push(supabase.from('hrv_records').select('player_id,measurement_date,rmssd_ms,ln_rmssd,resting_hr_bpm').eq('organization_id',ELITE).in('player_id',ids).order('measurement_date',{ascending:false}).limit(1000));const res=await Promise.all(req);setQ(res[0].data||[]);setRpe(res[1].data||[]);setPain(res[2].data||[]);setHrv(org===ELITE?(res[3]?.data||[]):[])}
 const rows=useMemo(()=>players.map(p=>{const qq=q.find(x=>x.player_id===p.id),rr=rpe.find(x=>x.player_id===p.id),pp=pain.find(x=>x.player_id===p.id),hh=hrv.find(x=>x.player_id===p.id);const a=qq?.answers||{};const hooper=a.hooper_total??sum([a.sleep_quality,a.fatigue,a.soreness,a.stress]);const computedSrpe=(rr?.rpe||0)*(rr?.actual_duration_min||0);return {...p,hooper,rpe:rr?.rpe??null,srpe:rr?.load_ua??(computedSrpe||null),pain:pp?.intensity??pp?.pain_intensity??null,rmssd:hh?.rmssd_ms??null,lnrmssd:hh?.ln_rmssd??null,rhr:hh?.resting_hr_bpm??null}}),[players,q,rpe,pain,hrv]);
 if(!ready)return <main style={S.center}>Chargement…</main>;if(!ok)return <main style={S.center}>Accès staff requis.</main>;
 return <main style={S.main}><header style={S.header}><div><span style={S.kicker}>SPORT & PERFORMANCE</span><h1 style={S.h1}>Monitoring journalier</h1><p style={S.sub}>Hooper · RPE Foster · sRPE · douleur{org===ELITE?' · HRV':''}. Lecture descriptive, sans diagnostic automatique.</p></div><a href='/admin/sport' style={S.back}>← Sport & Performance</a></header>
 <section style={S.filters}><label>Organisation<select value={org} onChange={e=>setOrg(e.target.value)} style={S.input}><option value={DIAMBARS}>DIAMBARS FC</option><option value={ELITE}>HDY ELITE</option></select></label>{org===DIAMBARS&&<label>Équipe<select value={team} onChange={e=>setTeam(e.target.value)} style={S.input}>{TEAMS.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label>}{org===ELITE&&<a href='/admin/sport/hrv' style={S.hrv}>Importer / analyser HRV →</a>}</section>
 <section style={S.card}><div style={S.tableWrap}><table style={S.table}><thead><tr><th>Athlète</th><th>Hooper /28</th><th>RPE</th><th>sRPE</th><th>Douleur</th>{org===ELITE&&<><th>RMSSD</th><th>LnRMSSD</th><th>FC repos</th></>}</tr></thead><tbody>{rows.map(x=><tr key={x.id}><td><b>{x.display_name||`${x.first_name} ${x.last_name}`}</b><small>{x.primary_position||x.position||'—'}</small></td><td>{show(x.hooper)}</td><td>{show(x.rpe)}</td><td>{show(x.srpe)}</td><td>{show(x.pain)}</td>{org===ELITE&&<><td>{show(x.rmssd)}</td><td>{show(x.lnrmssd)}</td><td>{show(x.rhr)}</td></>}</tr>)}</tbody></table></div>{!rows.length&&<p style={S.sub}>Aucun athlète dans ce périmètre.</p>}</section></main>
}
function num(v:any){const n=Number(v);return Number.isFinite(n)?n:null}function sum(v:any[]){const a=v.map(num);return a.every(x=>x!==null)?a.reduce((s,x)=>s+(x||0),0):null}function show(v:any){return v===null||v===undefined||v===''?'—':String(v)}
const S:Record<string,React.CSSProperties>={center:{minHeight:'80vh',display:'grid',placeItems:'center',fontFamily:'system-ui'},main:{minHeight:'100vh',background:'#09090B',color:'#FAFAFA',fontFamily:'Inter,system-ui,sans-serif',padding:28},header:{maxWidth:1280,margin:'0 auto 18px',display:'flex',justifyContent:'space-between',gap:20},kicker:{fontSize:11,fontWeight:900,letterSpacing:1.5,color:'#E31E24'},h1:{fontSize:'clamp(38px,5vw,64px)',margin:'4px 0',letterSpacing:-2.5},sub:{color:'#A1A1AA'},back:{color:'#fff',textDecoration:'none',border:'1px solid #2B2B31',borderRadius:10,padding:'10px 12px',height:'fit-content'},filters:{maxWidth:1280,margin:'0 auto 14px',display:'flex',gap:12,alignItems:'end',flexWrap:'wrap',background:'#141416',border:'1px solid #2B2B31',borderRadius:16,padding:14},input:{display:'block',minWidth:220,height:42,marginTop:6,background:'#1B1B1F',color:'#fff',border:'1px solid #34343A',borderRadius:10,padding:'0 10px'},hrv:{marginLeft:'auto',background:'#fff',color:'#111',textDecoration:'none',padding:'12px 14px',borderRadius:10,fontWeight:850},card:{maxWidth:1280,margin:'0 auto',background:'#141416',border:'1px solid #2B2B31',borderRadius:18,padding:16},tableWrap:{overflowX:'auto'},table:{width:'100%',borderCollapse:'collapse',fontSize:13}};