'use client';

import {useEffect,useMemo,useState} from 'react';
import {supabase} from '@/lib/supabase';

type Row=Record<string,string>;
type Player={id:string;display_name:string|null;first_name:string;last_name:string;team_id:string|null};
type Session={id:string;title:string;session_date:string;team_id:string|null};
const DIAMBARS='d3136b7f-ef28-43e8-af53-30fa6de70c62';
const PROA='d9bb5390-94cb-461e-b2cd-a326da2cfa3d';

function norm(s:string){return s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]/g,'')}
function pick(r:Row,keys:string[]){const entries=Object.entries(r);for(const k of keys){const n=norm(k);const hit=entries.find(([h])=>norm(h)===n);if(hit)return hit[1]}return ''}
function n(v:string){if(!v)return null;const x=Number(v.replace(',','.').replace(/\s/g,''));return Number.isFinite(x)?x:null}
function parseCsv(text:string){const first=text.split(/\r?\n/)[0]||'';const sep=(first.match(/;/g)||[]).length>(first.match(/,/g)||[]).length?';':',';const lines=text.split(/\r?\n/).filter(x=>x.trim());if(lines.length<2)return [] as Row[];const split=(line:string)=>line.split(sep).map(x=>x.trim().replace(/^"|"$/g,''));const head=split(lines[0]);return lines.slice(1).map(line=>{const a=split(line);const r:Row={};head.forEach((h,i)=>r[h]=a[i]??'');return r})}

export default function GPS(){
 const [ready,setReady]=useState(false),[ok,setOk]=useState(false),[players,setPlayers]=useState<Player[]>([]),[sessions,setSessions]=useState<Session[]>([]);
 const [rows,setRows]=useState<Row[]>([]),[provider,setProvider]=useState('GPS'),[sessionId,setSessionId]=useState(''),[msg,setMsg]=useState(''),[saving,setSaving]=useState(false);
 useEffect(()=>{(async()=>{const {data:{session}}=await supabase.auth.getSession();if(!session){setReady(true);return}const [{data:p},{data:m}]=await Promise.all([supabase.from('profiles').select('is_super_admin').eq('user_id',session.user.id).maybeSingle(),supabase.from('memberships').select('id').eq('user_id',session.user.id).eq('organization_id',DIAMBARS).eq('active',true).limit(1)]);if(p?.is_super_admin||m?.length)setOk(true);const [{data:pl},{data:ss}]=await Promise.all([supabase.from('players').select('id,display_name,first_name,last_name,team_id').eq('organization_id',DIAMBARS).eq('team_id',PROA).eq('active',true),supabase.from('sessions').select('id,title,session_date,team_id').eq('organization_id',DIAMBARS).eq('team_id',PROA).order('session_date',{ascending:false}).limit(30)]);setPlayers((pl||[]) as Player[]);setSessions((ss||[]) as Session[]);if(ss?.[0])setSessionId(ss[0].id);setReady(true)})()},[]);
 const preview=useMemo(()=>rows.map(r=>{const athlete=pick(r,['athlete','player','player name','name','joueur','nom','full name']);const p=players.find(x=>norm(x.display_name||`${x.first_name} ${x.last_name}`)===norm(athlete));return {athlete,player:p,total:n(pick(r,['total distance','total_distance','distance','distance total','distance totale'])),hsr:n(pick(r,['high speed running','hsr','high speed distance','distance high speed','distance haute intensite'])),sprint:n(pick(r,['sprint distance','sprint_distance','distance sprint'])),vmax:n(pick(r,['max speed','max_speed','vmax','vitesse max','top speed'])),acc:n(pick(r,['accelerations','acceleration count','accels','acc'])),dec:n(pick(r,['decelerations','deceleration count','decels','dec'])),duration:n(pick(r,['duration','duration min','minutes','duree','duree min'])),raw:r}}),[rows,players]);
 const matched=preview.filter(x=>x.player).length;
 async function file(f:File){setMsg('');const text=await f.text();const r=parseCsv(text);setRows(r);if(!r.length)setMsg('CSV vide ou format non reconnu.');}
 async function save(){if(!sessionId){setMsg('Sélectionne une séance.');return}if(!rows.length){setMsg('Charge un fichier CSV.');return}const valid=preview.filter(x=>x.player);if(!valid.length){setMsg('Aucun joueur du CSV n’a pu être associé automatiquement. Vérifie la colonne nom/joueur.');return}setSaving(true);const session=sessions.find(s=>s.id===sessionId);const payload=valid.map(x=>({organization_id:DIAMBARS,session_id:sessionId,player_id:x.player!.id,provider:provider||null,device_id:null,metrics:{total_distance_m:x.total,high_speed_distance_m:x.hsr,sprint_distance_m:x.sprint,max_speed_kmh:x.vmax,accelerations:x.acc,decelerations:x.dec,duration_min:x.duration,raw:x.raw},thresholds_version:null,individualization_method:'provider_export',source:'csv',recorded_at:session?.session_date?`${session.session_date}T12:00:00Z`:new Date().toISOString()}));const {error}=await supabase.from('gps_records').insert(payload);setSaving(false);if(error){setMsg(error.message);return}setMsg(`${payload.length} ligne(s) GPS importée(s) et rattachée(s) à la séance.`);setRows([])}
 if(!ready)return <main style={S.center}>Chargement…</main>;if(!ok)return <main style={S.center}>Accès staff Diambars requis.</main>;
 return <main style={S.main}><header style={S.header}><div><span style={S.kicker}>DIAMBARS FC · GPS</span><h1 style={S.h1}>Import charge externe</h1><p style={S.sub}>CSV → joueur → séance → gps_records. Le fichier source complet est conservé dans metrics.raw pour pouvoir remapper un fournisseur plus tard.</p></div><a href='/admin/sport' style={S.back}>← Sport & Performance</a></header>
 <section style={S.card}><div style={S.grid}><label>Fournisseur<input value={provider} onChange={e=>setProvider(e.target.value)} style={S.input} placeholder='Ex. Catapult, STATSports, WIMU…'/></label><label>Séance<select value={sessionId} onChange={e=>setSessionId(e.target.value)} style={S.input}>{sessions.map(s=><option key={s.id} value={s.id}>{s.session_date} · {s.title}</option>)}</select></label><label>Fichier CSV<input type='file' accept='.csv,text/csv' onChange={e=>e.target.files?.[0]&&file(e.target.files[0])} style={S.file}/></label></div>{msg&&<p style={S.notice}>{msg}</p>}{rows.length>0&&<><div style={S.stat}><b>{rows.length}</b> lignes détectées · <b>{matched}</b> joueurs associés automatiquement · <b>{rows.length-matched}</b> à vérifier</div><div style={S.tableWrap}><table style={S.table}><thead><tr><th>Joueur CSV</th><th>Association</th><th>Distance</th><th>HSR</th><th>Sprint</th><th>Vmax</th><th>Acc</th><th>Dec</th></tr></thead><tbody>{preview.slice(0,40).map((x,i)=><tr key={i}><td>{x.athlete||'—'}</td><td>{x.player?(x.player.display_name||`${x.player.first_name} ${x.player.last_name}`):'NON ASSOCIÉ'}</td><td>{x.total??'—'}</td><td>{x.hsr??'—'}</td><td>{x.sprint??'—'}</td><td>{x.vmax??'—'}</td><td>{x.acc??'—'}</td><td>{x.dec??'—'}</td></tr>)}</tbody></table></div><button onClick={save} disabled={saving||matched===0} style={S.button}>{saving?'Import…':`Importer ${matched} joueur(s)`}</button></>}</section>
 </main>}
const S:Record<string,React.CSSProperties>={center:{minHeight:'80vh',display:'grid',placeItems:'center',fontFamily:'system-ui'},main:{minHeight:'100vh',background:'#09090B',color:'#FAFAFA',fontFamily:'Inter,system-ui,sans-serif',padding:28},header:{maxWidth:1280,margin:'0 auto 18px',display:'flex',justifyContent:'space-between',gap:20,flexWrap:'wrap'},kicker:{fontSize:11,fontWeight:900,letterSpacing:1.5,color:'#E31E24'},h1:{fontSize:'clamp(38px,5vw,64px)',margin:'4px 0',letterSpacing:-2.5},sub:{color:'#A1A1AA',maxWidth:800},back:{color:'#fff',textDecoration:'none',border:'1px solid #2B2B31',borderRadius:10,padding:'10px 12px',height:'fit-content'},card:{maxWidth:1280,margin:'0 auto',background:'#141416',border:'1px solid #2B2B31',borderRadius:18,padding:16},grid:{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(220px,1fr))',gap:12},input:{display:'block',width:'100%',boxSizing:'border-box',height:44,marginTop:6,background:'#1B1B1F',color:'#fff',border:'1px solid #34343A',borderRadius:10,padding:'0 10px'},file:{display:'block',marginTop:12,color:'#ddd'},notice:{background:'#211719',border:'1px solid #4A2327',padding:12,borderRadius:10,color:'#FFD1D3'},stat:{margin:'16px 0',padding:12,background:'#19191C',borderRadius:10},tableWrap:{overflowX:'auto'},table:{width:'100%',borderCollapse:'collapse',fontSize:12},button:{marginTop:14,height:46,border:0,borderRadius:10,padding:'0 18px',background:'#E31E24',color:'#fff',fontWeight:900}}