'use client';

import {useEffect,useMemo,useState} from 'react';
import * as XLSX from 'xlsx';
import {supabase} from '@/lib/supabase';

type Row=Record<string,string>;
type Player={id:string;display_name:string|null;first_name:string;last_name:string;team_id:string|null};
type Session={id:string;title:string;session_date:string;team_id:string|null};
type GpsInserted={id:string;player_id:string;recorded_at:string;metrics:Record<string,any>};
const DIAMBARS='d3136b7f-ef28-43e8-af53-30fa6de70c62';
const PROA='d9bb5390-94cb-461e-b2cd-a326da2cfa3d';
const ACWR_WATCH=1.30;
const ACWR_HIGH=1.50;
function norm(s:string){return String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]/g,'')}
function pick(r:Row,keys:string[]){for(const [h,v] of Object.entries(r)){if(keys.some(k=>norm(k)===norm(h)))return String(v??'')}return ''}
function num(v:any){if(v===null||v===undefined||v==='')return null;const x=Number(String(v).replace(',','.').replace(/\s/g,''));return Number.isFinite(x)?x:null}
function csv(text:string){const first=text.split(/\r?\n/)[0]||'';const sep=(first.match(/;/g)||[]).length>(first.match(/,/g)||[]).length?';':',';const lines=text.split(/\r?\n/).filter(x=>x.trim());if(lines.length<2)return [] as Row[];const split=(line:string)=>line.split(sep).map(x=>x.trim().replace(/^"|"$/g,''));const head=split(lines[0]);return lines.slice(1).map(line=>{const a=split(line);const r:Row={};head.forEach((h,i)=>r[h]=a[i]??'');return r})}
function isoDate(v:string){if(!v)return null;const n=Number(v);if(Number.isFinite(n)&&n>30000){const d=XLSX.SSF.parse_date_code(n);if(d)return `${d.y}-${String(d.m).padStart(2,'0')}-${String(d.d).padStart(2,'0')}`}const d=new Date(v);return Number.isNaN(d.getTime())?null:d.toISOString().slice(0,10)}
function ymd(d:Date){return d.toISOString().slice(0,10)}
function alertLevel(acwr:number|null){if(acwr===null)return null;if(acwr>=ACWR_HIGH)return 'red';if(acwr>=ACWR_WATCH)return 'orange';return null}
function alertText(acwr:number|null){const l=alertLevel(acwr);return l==='red'?'ALERTE':l==='orange'?'VIGILANCE':'—'}

export default function GPS(){
 const [ready,setReady]=useState(false),[ok,setOk]=useState(false),[players,setPlayers]=useState<Player[]>([]),[sessions,setSessions]=useState<Session[]>([]);
 const [rows,setRows]=useState<Row[]>([]),[provider,setProvider]=useState('GPS / Numbers'),[sessionId,setSessionId]=useState(''),[selectedPlayer,setSelectedPlayer]=useState(''),[mode,setMode]=useState<'session'|'history'>('session'),[msg,setMsg]=useState(''),[saving,setSaving]=useState(false),[fileName,setFileName]=useState('');
 useEffect(()=>{(async()=>{const {data:{session}}=await supabase.auth.getSession();if(!session){setReady(true);return}const [{data:p},{data:m}]=await Promise.all([supabase.from('profiles').select('is_super_admin').eq('user_id',session.user.id).maybeSingle(),supabase.from('memberships').select('id').eq('user_id',session.user.id).eq('organization_id',DIAMBARS).eq('active',true).limit(1)]);if(p?.is_super_admin||m?.length)setOk(true);const [{data:pl},{data:ss}]=await Promise.all([supabase.from('players').select('id,display_name,first_name,last_name,team_id').eq('organization_id',DIAMBARS).eq('team_id',PROA).eq('active',true).order('display_name'),supabase.from('sessions').select('id,title,session_date,team_id').eq('organization_id',DIAMBARS).eq('team_id',PROA).order('session_date',{ascending:false}).limit(50)]);setPlayers((pl||[]) as Player[]);setSessions((ss||[]) as Session[]);if(pl?.[0])setSelectedPlayer(pl[0].id);if(ss?.[0])setSessionId(ss[0].id);setReady(true)})()},[]);
 const preview=useMemo(()=>rows.map(r=>{const athlete=pick(r,['athlete','player','player name','name','joueur','nom','full name']);const detected=players.find(x=>norm(x.display_name||`${x.first_name} ${x.last_name}`)===norm(athlete));const p=detected||players.find(x=>x.id===selectedPlayer);return {date:isoDate(pick(r,['date','jour','session date'])),athlete,player:p,total:num(pick(r,['total distance','total_distance','distance','distance total','distance totale','total distance (km)'])),hsr:num(pick(r,['high speed running','hsr','high speed distance','distance high speed','distance haute intensite','high intensity distance (km)'])),sprint:num(pick(r,['sprint distance','sprint_distance','distance sprint','sprint distance (km)'])),sprintCount:num(pick(r,['sprint count','sprints','number of sprints'])),vmax:num(pick(r,['max speed','max_speed','vmax','vitesse max','top speed','max speed (km/h)'])),acc:num(pick(r,['accelerations','acceleration count','accels','acc','accelerations >3'])),dec:num(pick(r,['decelerations','deceleration count','decels','dec','decelerations >3'])),duration:num(pick(r,['duration','duration min','minutes','duree','duree min','duration (min)'])),rpe:num(pick(r,['rpe'])),internal:num(pick(r,['internal load','internal load (au)'])),external:num(pick(r,['external load','player load','player loading','player_load','playerload'])),acute:num(pick(r,['acute load 7d'])),chronic:num(pick(r,['chronic load 28d'])),acwr:num(pick(r,['acwr'])),sessionType:pick(r,['session type','type']),theme:pick(r,['theme','séance','session']),raw:r}}),[rows,players,selectedPlayer]);
 async function loadFile(f:File){setMsg('');setFileName(f.name);if(/\.xlsx?$/i.test(f.name)){const ab=await f.arrayBuffer();const wb=XLSX.read(ab,{type:'array'});const sheet=wb.Sheets[wb.SheetNames.includes('All Sessions')?'All Sessions':wb.SheetNames[0]];const parsed=XLSX.utils.sheet_to_json<Record<string,unknown>>(sheet,{defval:''}).map(o=>Object.fromEntries(Object.entries(o).map(([k,v])=>[k,String(v??'')])) as Row);setRows(parsed);if(parsed.some(r=>pick(r,['date'])))setMode('history');if(!parsed.length)setMsg('Aucune ligne détectée dans le fichier Excel.');return}const parsed=csv(await f.text());setRows(parsed);if(!parsed.length)setMsg('CSV vide ou format non reconnu.');}
 async function existingHistoryDates(playerId:string,valid:any[]){const dates=valid.map(x=>x.date).filter(Boolean).sort();if(!dates.length)return new Set<string>();const {data}=await supabase.from('gps_records').select('recorded_at').eq('player_id',playerId).eq('source','xlsx_historical').gte('recorded_at',`${dates[0]}T00:00:00Z`).lte('recorded_at',`${dates[dates.length-1]}T23:59:59Z`);return new Set((data||[]).map((x:any)=>String(x.recorded_at).slice(0,10)))}
 async function writeAutomaticAlert(record:GpsInserted,acwr:number){const level=alertLevel(acwr);if(!level)return;const {data:existing}=await supabase.from('alerts').select('id').eq('player_id',record.player_id).eq('status','open').contains('related_data',{gps_record_id:record.id}).limit(1);if(existing?.length)return;await supabase.from('alerts').insert({organization_id:DIAMBARS,player_id:record.player_id,level,reason:`ACWR ${acwr.toFixed(2)} — revue staff médical / performance requise`,related_data:{type:'acwr',acwr,gps_record_id:record.id,recorded_at:record.recorded_at,rule_version:'acwr_v1',watch_threshold:ACWR_WATCH,high_threshold:ACWR_HIGH},status:'open'});}
 async function calculateAndStoreAcwr(record:GpsInserted){const currentExt=num(record.metrics?.external_load);const sourceAcwr=num(record.metrics?.acwr);if(sourceAcwr!==null){await writeAutomaticAlert(record,sourceAcwr);return}if(currentExt===null)return;const end=new Date(record.recorded_at);const start28=new Date(end);start28.setUTCDate(start28.getUTCDate()-27);const {data}=await supabase.from('gps_records').select('recorded_at,metrics').eq('player_id',record.player_id).gte('recorded_at',start28.toISOString()).lte('recorded_at',`${ymd(end)}T23:59:59Z`);const daily=new Map<string,number>();for(const x of data||[]){const load=num((x as any).metrics?.external_load);if(load===null)continue;const d=String((x as any).recorded_at).slice(0,10);daily.set(d,(daily.get(d)||0)+load)}const start7=new Date(end);start7.setUTCDate(start7.getUTCDate()-6);let acute=0,total28=0;for(const [d,v] of daily){total28+=v;if(d>=ymd(start7)&&d<=ymd(end))acute+=v}const chronic=total28/4;const acwr=chronic>0?acute/chronic:null;if(acwr===null)return;const metrics={...record.metrics,acute_load_7d:Math.round(acute*100)/100,chronic_load_28d:Math.round(chronic*100)/100,acwr:Math.round(acwr*100)/100,acwr_method:'acute_7d_sum / (28d_sum / 4)'};await supabase.from('gps_records').update({metrics}).eq('id',record.id);record.metrics=metrics;await writeAutomaticAlert(record,acwr)}
 async function save(){if(!rows.length){setMsg('Charge un fichier CSV ou Excel.');return}if(mode==='session'&&!sessionId){setMsg('Sélectionne une séance.');return}let valid=preview.filter(x=>x.player&&(mode==='session'||x.date));if(!valid.length){setMsg('Aucune ligne exploitable. Pour un historique Excel, vérifie la colonne Date et sélectionne le joueur.');return}setSaving(true);if(mode==='history'){const dates=await existingHistoryDates(selectedPlayer,valid);valid=valid.filter(x=>x.date&&!dates.has(x.date));if(!valid.length){setSaving(false);setMsg('Toutes les dates de cet historique sont déjà présentes dans le dossier joueur. Aucun doublon ajouté.');return}}const sess=sessions.find(s=>s.id===sessionId);const payload=valid.map(x=>({organization_id:DIAMBARS,session_id:mode==='session'?sessionId:null,player_id:x.player!.id,provider:provider||null,device_id:null,metrics:{session_type:x.sessionType||null,theme:x.theme||null,total_distance_km:x.total,high_intensity_distance_km:x.hsr,sprint_distance_km:x.sprint,sprint_count:x.sprintCount,max_speed_kmh:x.vmax,accelerations_gt3:x.acc,decelerations_gt3:x.dec,duration_min:x.duration,rpe_historical:mode==='history'?x.rpe:null,internal_load_au:mode==='history'?x.internal:null,external_load:x.external,acute_load_7d:x.acute,chronic_load_28d:x.chronic,acwr:x.acwr,raw:x.raw,source_file:fileName},thresholds_version:'acwr_v1',individualization_method:mode==='history'?'source_workbook':'provider_export',source:mode==='history'?'xlsx_historical':'gps_session',recorded_at:mode==='history'?`${x.date}T12:00:00Z`:(sess?.session_date?`${sess.session_date}T12:00:00Z`:new Date().toISOString())}));const {data:inserted,error}=await supabase.from('gps_records').insert(payload).select('id,player_id,recorded_at,metrics');if(error){setSaving(false);setMsg(error.message);return}if(mode==='session'){for(const r of (inserted||[]) as GpsInserted[])await calculateAndStoreAcwr(r)}setSaving(false);setMsg(`${payload.length} ligne(s) importée(s) dans le dossier joueur${mode==='session'?' · ACWR et alertes recalculés automatiquement lorsque la charge externe est disponible':''}.`);setRows([])}
 if(!ready)return <main style={S.center}>Chargement…</main>;if(!ok)return <main style={S.center}>Accès staff Diambars requis.</main>;
 const matched=preview.filter(x=>x.player&&(mode==='session'||x.date)).length;
 return <main style={S.main}><header style={S.header}><div><span style={S.kicker}>DIAMBARS FC · GPS</span><h1 style={S.h1}>Import charge externe</h1><p style={S.sub}>Compatible CSV GPS et Excel/Numbers converti en .xlsx. En mode séance, l’ACWR est calculé automatiquement à partir de la charge externe disponible et peut générer une alerte de revue staff.</p></div><a href='/admin/sport' style={S.back}>← Sport & Performance</a></header><section style={S.card}><div style={S.rule}><b>Règle pilote ACWR</b><span>Vigilance ≥ {ACWR_WATCH.toFixed(2)} · Alerte staff médical/performance ≥ {ACWR_HIGH.toFixed(2)} · aucune décision médicale automatique.</span></div><div style={S.mode}><button onClick={()=>setMode('session')} style={mode==='session'?S.active:S.ghost}>Séance GPS</button><button onClick={()=>setMode('history')} style={mode==='history'?S.active:S.ghost}>Historique Excel</button></div><div style={S.grid}><label>Joueur<select value={selectedPlayer} onChange={e=>setSelectedPlayer(e.target.value)} style={S.input}>{players.map(p=><option key={p.id} value={p.id}>{p.display_name||`${p.first_name} ${p.last_name}`}</option>)}</select></label><label>Fournisseur<input value={provider} onChange={e=>setProvider(e.target.value)} style={S.input}/></label>{mode==='session'&&<label>Séance<select value={sessionId} onChange={e=>setSessionId(e.target.value)} style={S.input}>{sessions.map(s=><option key={s.id} value={s.id}>{s.session_date} · {s.title}</option>)}</select></label>}<label>Fichier<input type='file' accept='.csv,.xlsx,.xls,text/csv,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' onChange={e=>e.target.files?.[0]&&loadFile(e.target.files[0])} style={S.file}/></label></div>{msg&&<p style={S.notice}>{msg}</p>}{rows.length>0&&<><div style={S.stat}><b>{rows.length}</b> lignes détectées · <b>{matched}</b> exploitables · mode <b>{mode==='history'?'historique':'séance'}</b></div><div style={S.tableWrap}><table style={S.table}><thead><tr><th>Date</th><th>Joueur</th><th>Distance km</th><th>HID km</th><th>Sprint km</th><th>Sprints</th><th>Vmax</th><th>Acc</th><th>Dec</th><th>RPE hist.</th><th>Player/Ext. load</th><th>ACWR</th><th>Signal</th></tr></thead><tbody>{preview.slice(0,50).map((x,i)=><tr key={i}><td>{x.date||'—'}</td><td>{x.player?(x.player.display_name||`${x.player.first_name} ${x.player.last_name}`):'NON ASSOCIÉ'}</td><td>{x.total??'—'}</td><td>{x.hsr??'—'}</td><td>{x.sprint??'—'}</td><td>{x.sprintCount??'—'}</td><td>{x.vmax??'—'}</td><td>{x.acc??'—'}</td><td>{x.dec??'—'}</td><td>{x.rpe??'—'}</td><td>{x.external??'—'}</td><td>{x.acwr??'auto'}</td><td><b>{alertText(x.acwr)}</b></td></tr>)}</tbody></table></div><button onClick={save} disabled={saving||matched===0} style={S.button}>{saving?'Import et calcul…':`Importer ${matched} ligne(s)`}</button></>}</section></main>}
const S:Record<string,React.CSSProperties>={center:{minHeight:'80vh',display:'grid',placeItems:'center',fontFamily:'system-ui'},main:{minHeight:'100vh',background:'#09090B',color:'#FAFAFA',fontFamily:'Inter,system-ui,sans-serif',padding:28},header:{maxWidth:1280,margin:'0 auto 18px',display:'flex',justifyContent:'space-between',gap:20,flexWrap:'wrap'},kicker:{fontSize:11,fontWeight:900,letterSpacing:1.5,color:'#E31E24'},h1:{fontSize:'clamp(38px,5vw,64px)',margin:'4px 0',letterSpacing:-2.5},sub:{color:'#A1A1AA',maxWidth:850},back:{color:'#fff',textDecoration:'none',border:'1px solid #2B2B31',borderRadius:10,padding:'10px 12px',height:'fit-content'},card:{maxWidth:1280,margin:'0 auto',background:'#141416',border:'1px solid #2B2B31',borderRadius:18,padding:16},rule:{display:'grid',gap:4,marginBottom:14,padding:12,border:'1px solid #5A2A2E',background:'#211719',borderRadius:12},mode:{display:'flex',gap:8,marginBottom:14},active:{border:0,borderRadius:9,padding:'10px 12px',background:'#E31E24',color:'#fff',fontWeight:900},ghost:{border:'1px solid #38383D',borderRadius:9,padding:'10px 12px',background:'#1A1A1D',color:'#fff'},grid:{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(220px,1fr))',gap:12},input:{display:'block',width:'100%',boxSizing:'border-box',height:44,marginTop:6,background:'#1B1B1F',color:'#fff',border:'1px solid #34343A',borderRadius:10,padding:'0 10px'},file:{display:'block',marginTop:12,color:'#ddd'},notice:{background:'#211719',border:'1px solid #4A2327',padding:12,borderRadius:10,color:'#FFD1D3'},stat:{margin:'16px 0',padding:12,background:'#19191C',borderRadius:10},tableWrap:{overflowX:'auto'},table:{width:'100%',borderCollapse:'collapse',fontSize:12},button:{marginTop:14,height:46,border:0,borderRadius:10,padding:'0 18px',background:'#E31E24',color:'#fff',fontWeight:900}}