'use client';

import {useEffect,useMemo,useState} from 'react';
import {supabase} from '@/lib/supabase';

type Row=Record<string,any>;
const DIAMBARS='d3136b7f-ef28-43e8-af53-30fa6de70c62';

export default function Alerts(){
 const [ready,setReady]=useState(false),[ok,setOk]=useState(false),[alerts,setAlerts]=useState<Row[]>([]),[players,setPlayers]=useState<Row[]>([]),[showClosed,setShowClosed]=useState(false),[msg,setMsg]=useState('');
 useEffect(()=>{(async()=>{const {data:{session}}=await supabase.auth.getSession();if(!session){setReady(true);return}const [{data:p},{data:m}]=await Promise.all([supabase.from('profiles').select('is_super_admin').eq('user_id',session.user.id).maybeSingle(),supabase.from('memberships').select('id').eq('user_id',session.user.id).eq('organization_id',DIAMBARS).eq('active',true).limit(1)]);if(!p?.is_super_admin&&!m?.length){setReady(true);return}setOk(true);await load();setReady(true)})()},[]);
 async function load(){const [{data:a},{data:p}]=await Promise.all([supabase.from('alerts').select('*').eq('organization_id',DIAMBARS).order('created_at',{ascending:false}).limit(300),supabase.from('players').select('id,display_name,first_name,last_name,team_id').eq('organization_id',DIAMBARS)]);setAlerts((a||[]) as Row[]);setPlayers((p||[]) as Row[])}
 const rows=useMemo(()=>alerts.filter(a=>showClosed||a.status!=='closed').map(a=>({...a,player:players.find(p=>p.id===a.player_id)})),[alerts,players,showClosed]);
 async function setStatus(id:string,status:string){setMsg('');const {error}=await supabase.from('alerts').update({status}).eq('id',id);if(error){setMsg(error.message);return}setAlerts(x=>x.map(a=>a.id===id?{...a,status}:a));}
 if(!ready)return <main style={S.center}>Chargement…</main>;if(!ok)return <main style={S.center}>Accès staff Diambars requis.</main>;
 return <main style={S.main}><header style={S.header}><div><span style={S.kicker}>DIAMBARS FC · STAFF</span><h1 style={S.h1}>Alertes médicales & performance</h1><p style={S.sub}>Signaux automatiques destinés à déclencher une revue humaine. Une alerte n’est ni un diagnostic ni une exclusion automatique du joueur.</p></div><a href='/admin/sport' style={S.back}>← Sport & Performance</a></header><section style={S.filters}><label style={S.check}><input type='checkbox' checked={showClosed} onChange={e=>setShowClosed(e.target.checked)}/> Afficher les alertes clôturées</label><a href='/admin/sport/monitoring' style={S.link}>Monitoring →</a></section>{msg&&<p style={S.notice}>{msg}</p>}<section style={S.list}>{rows.map(a=>{const name=a.player?.display_name||`${a.player?.first_name||''} ${a.player?.last_name||''}`.trim()||'Joueur';const acwr=a.related_data?.acwr;return <article key={a.id} style={{...S.card,borderColor:a.level==='red'?'#B91C1C':a.level==='orange'?'#A16207':'#2B2B31'}}><div style={S.top}><span style={{...S.badge,background:a.level==='red'?'#7F1D1D':a.level==='orange'?'#713F12':'#27272A'}}>{a.level==='red'?'ALERTE':a.level==='orange'?'VIGILANCE':'INFO'}</span><span style={S.date}>{new Date(a.created_at).toLocaleString('fr-FR')}</span></div><h2 style={S.h2}><a href={a.player_id?`/admin/sport/players/${a.player_id}`:'#'} style={S.player}>{name}</a></h2><p>{a.reason}</p><div style={S.meta}>{acwr!==undefined&&<span>ACWR <b>{Number(acwr).toFixed(2)}</b></span>}<span>Statut <b>{a.status}</b></span>{a.related_data?.recorded_at&&<span>Donnée du <b>{new Date(a.related_data.recorded_at).toLocaleDateString('fr-FR')}</b></span>}</div><div style={S.actions}>{a.status==='open'&&<button onClick={()=>setStatus(a.id,'acknowledged')} style={S.ghost}>Acquitter</button>}{a.status!=='closed'&&<button onClick={()=>setStatus(a.id,'closed')} style={S.button}>Clôturer après revue</button>}</div></article>})}{!rows.length&&<article style={S.card}><h2>Aucune alerte dans ce filtre</h2><p style={S.sub}>Les nouvelles alertes ACWR apparaîtront ici après import d’une séance GPS avec charge externe exploitable.</p></article>}</section></main>}
const S:Record<string,React.CSSProperties>={center:{minHeight:'80vh',display:'grid',placeItems:'center',fontFamily:'system-ui'},main:{minHeight:'100vh',background:'#09090B',color:'#FAFAFA',fontFamily:'Inter,system-ui,sans-serif',padding:28},header:{maxWidth:1100,margin:'0 auto 18px',display:'flex',justifyContent:'space-between',gap:20,flexWrap:'wrap'},kicker:{fontSize:11,fontWeight:900,letterSpacing:1.5,color:'#E31E24'},h1:{fontSize:'clamp(36px,5vw,62px)',margin:'4px 0',letterSpacing:-2.2},sub:{color:'#A1A1AA',maxWidth:760},back:{color:'#fff',textDecoration:'none',border:'1px solid #2B2B31',borderRadius:10,padding:'10px 12px',height:'fit-content'},filters:{maxWidth:1100,margin:'0 auto 14px',display:'flex',justifyContent:'space-between',gap:12,alignItems:'center',flexWrap:'wrap',background:'#141416',border:'1px solid #2B2B31',borderRadius:14,padding:12},check:{display:'flex',gap:8,alignItems:'center'},link:{color:'#fff',textDecoration:'none',fontWeight:800},notice:{maxWidth:1100,margin:'0 auto 14px',background:'#211719',border:'1px solid #4A2327',padding:12,borderRadius:10,color:'#FFD1D3'},list:{maxWidth:1100,margin:'0 auto',display:'grid',gap:12},card:{background:'#141416',border:'1px solid #2B2B31',borderRadius:16,padding:16},top:{display:'flex',justifyContent:'space-between',gap:12,alignItems:'center'},badge:{padding:'5px 8px',borderRadius:999,fontSize:10,fontWeight:900,letterSpacing:.8},date:{color:'#A1A1AA',fontSize:12},h2:{margin:'10px 0 6px'},player:{color:'#fff',textDecoration:'none'},meta:{display:'flex',gap:16,flexWrap:'wrap',fontSize:12,color:'#A1A1AA',marginTop:10},actions:{display:'flex',gap:8,marginTop:14,flexWrap:'wrap'},button:{border:0,borderRadius:9,padding:'10px 12px',background:'#E31E24',color:'#fff',fontWeight:850},ghost:{border:'1px solid #3F3F46',borderRadius:9,padding:'10px 12px',background:'#1A1A1D',color:'#fff',fontWeight:800}}