'use client';

import { useEffect, useMemo, useState } from 'react';
import { supabase } from '@/lib/supabase';

type Row=Record<string,any>;
const DIAMBARS='d3136b7f-ef28-43e8-af53-30fa6de70c62';
const ELITE='5454ad8f-8f2b-4812-9923-ab7d0b1f8748';
const TEAMS=[{id:'d9bb5390-94cb-461e-b2cd-a326da2cfa3d',name:'PRO A'},{id:'44f6976d-f5ef-4dcf-980f-ce3995e99877',name:'U19 · PRO B'},{id:'28b38b9f-3de0-419d-8275-b331a074b7f4',name:'U17'},{id:'e652df98-4653-416c-b794-3763e38a629d',name:'U15'}];
const PERMS=['manage_players','manage_monitoring','manage_tests','manage_teams','manage_users','manage_exports','all_settings'];
const ROLES=['organization_admin','direction','medical','performance','coach','recruitment','staff'];

export default function Manage(){
 const [ready,setReady]=useState(false),[ok,setOk]=useState(false),[msg,setMsg]=useState('');
 const [org,setOrg]=useState(DIAMBARS),[team,setTeam]=useState(TEAMS[2].id),[tab,setTab]=useState<'player'|'tests'|'staff'>('player');
 const [players,setPlayers]=useState<Row[]>([]),[defs,setDefs]=useState<Row[]>([]),[members,setMembers]=useState<Row[]>([]),[profiles,setProfiles]=useState<Row[]>([]);
 const [playerId,setPlayerId]=useState(''),[draft,setDraft]=useState<Row>({});
 const [testPlayer,setTestPlayer]=useState(''),[defId,setDefId]=useState(''),[trials,setTrials]=useState(''),[device,setDevice]=useState(''),[testedAt,setTestedAt]=useState(new Date().toISOString().slice(0,16));
 const isD=org===DIAMBARS; const theme=isD?{bg:'#09090B',surface:'#141416',surface2:'#1B1B1F',border:'#2B2B31',text:'#FAFAFA',muted:'#92929B',accent:'#E31E24'}:{bg:'#F4F4F5',surface:'#fff',surface2:'#F7F7F8',border:'#E4E4E7',text:'#111',muted:'#71717A',accent:'#111'};
 async function reload(){
  const [p,d,m,pr]=await Promise.all([supabase.from('players').select('*').eq('active',true),supabase.from('test_definitions').select('*').eq('active',true),supabase.from('memberships').select('*'),supabase.from('profiles').select('user_id,full_name,is_super_admin')]);
  setPlayers(p.data||[]);setDefs(d.data||[]);setMembers(m.data||[]);setProfiles(pr.data||[]);
 }
 useEffect(()=>{(async()=>{const {data:{session}}=await supabase.auth.getSession();if(!session){setReady(true);return}const {data}=await supabase.from('profiles').select('is_super_admin').eq('user_id',session.user.id).maybeSingle();if(!data?.is_super_admin){setReady(true);return}setOk(true);await reload();setReady(true)})()},[]);
 useEffect(()=>{if(!isD)setTeam('');else if(!TEAMS.some(x=>x.id===team))setTeam(TEAMS[2].id)},[org,isD,team]);
 const scoped=useMemo(()=>players.filter(p=>p.organization_id===org&&(!isD||p.team_id===team)),[players,org,team,isD]);
 const selected=players.find(p=>p.id===playerId)||scoped[0];
 useEffect(()=>{if(selected){setPlayerId(selected.id);setDraft({...selected})}},[selected?.id]);
 useEffect(()=>{if(!testPlayer&&scoped[0])setTestPlayer(scoped[0].id)},[scoped,testPlayer]);
 const visibleDefs=defs.filter(d=>d.organization_id===org||d.organization_id===null);
 useEffect(()=>{if(!visibleDefs.some(d=>d.id===defId))setDefId(visibleDefs[0]?.id||'')},[org,defs,defId]);
 async function savePlayer(){if(!selected)return;setMsg('Enregistrement…');const payload:any={};for(const k of ['first_name','last_name','preferred_name','sex','birth_date','birth_place','license_number','phone','email','address','city','country','dossier_status','category','season','jersey_number','primary_position','dominant_foot','weak_foot_level','height_cm','weight_kg','wingspan_cm','club_arrival_date','contract_type','contract_start_date','contract_end_date','selections','agent_name','agent_phone','agent_email'])payload[k]=draft[k]===''?null:draft[k];payload.nationalities=arr(draft.nationalities);payload.languages=arr(draft.languages);payload.secondary_positions=arr(draft.secondary_positions);payload.promoted_age_group=!!draft.promoted_age_group;payload.updated_at=new Date().toISOString();const {error}=await supabase.from('players').update(payload).eq('id',selected.id);setMsg(error?error.message:'Dossier joueur enregistré ✓');if(!error)await reload()}
 async function saveTest(){const def=defs.find(d=>d.id===defId);const vals=trials.split(',').map(v=>Number(v.trim())).filter(Number.isFinite);if(!testPlayer||!def||!vals.length){setMsg('Sélectionne un joueur, un test et au moins une valeur.');return}const best=def.best_rule==='min'?Math.min(...vals):Math.max(...vals);const mean=vals.reduce((a,b)=>a+b,0)/vals.length;const {data:{session}}=await supabase.auth.getSession();const {error}=await supabase.from('test_results').insert({organization_id:org,test_definition_id:def.id,player_id:testPlayer,tested_at:new Date(testedAt).toISOString(),trials:vals,best_value:best,mean_value:mean,device:device||null,evaluator_user_id:session?.user.id||null,context:{protocol:def.protocol,unit:def.unit}});setMsg(error?error.message:`${def.name} enregistré : ${best} ${def.unit} ✓`);if(!error){setTrials('');setDevice('');await reload()}}
 async function patchMember(id:string,patch:Row){const {error}=await supabase.from('memberships').update(patch).eq('id',id);setMsg(error?error.message:'Droits staff enregistrés ✓');if(!error)await reload()}
 if(!ready)return <main style={S.center}>Chargement…</main>; if(!ok)return <main style={S.center}>Accès administrateur principal requis.</main>;
 return <main style={{minHeight:'100vh',background:theme.bg,color:theme.text,fontFamily:'Inter,system-ui,sans-serif'}}><header style={{...S.header,background:theme.surface,borderColor:theme.border}}><a href='/admin/workspace' style={{...S.back,color:theme.text,borderColor:theme.border}}>← Dashboard</a><div><b>HDY PERFORMANCE ENGINE</b><small style={{display:'block',color:theme.muted}}>Saisie & administration</small></div></header><section style={S.wrap}>
 <div style={{...S.switcher,background:theme.surface,borderColor:theme.border}}><label>ORGANISATION<select value={org} onChange={e=>setOrg(e.target.value)} style={field(theme)}><option value={DIAMBARS}>DIAMBARS FC</option><option value={ELITE}>HDY ELITE</option></select></label>{isD&&<label>ÉQUIPE<select value={team} onChange={e=>setTeam(e.target.value)} style={field(theme)}>{TEAMS.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label>}</div>
 <nav style={{...S.tabs,background:theme.surface,borderColor:theme.border}}><button onClick={()=>setTab('player')} style={tabStyle(tab==='player',theme)}>Fiche joueur</button><button onClick={()=>setTab('tests')} style={tabStyle(tab==='tests',theme)}>Saisie tests</button><button onClick={()=>setTab('staff')} style={tabStyle(tab==='staff',theme)}>Droits staff</button></nav>{msg&&<div style={{...S.notice,borderColor:theme.border,background:theme.surface}}>{msg}</div>}
 {tab==='player'&&<div style={S.grid2}><aside style={{...S.card,background:theme.surface,borderColor:theme.border}}><h2>Joueurs</h2>{scoped.map(p=><button key={p.id} onClick={()=>setPlayerId(p.id)} style={{...S.person,background:selected?.id===p.id?theme.accent:theme.surface2,color:selected?.id===p.id?'#fff':theme.text,borderColor:theme.border}}><b>{p.display_name||`${p.first_name} ${p.last_name}`}</b><small>{p.primary_position||p.position||'—'}</small></button>)}</aside><section style={{...S.card,background:theme.surface,borderColor:theme.border}}>{selected&&<><div style={S.cardHead}><div><small style={{color:theme.muted}}>DOSSIER LONGITUDINAL</small><h1>{selected.display_name||`${selected.first_name} ${selected.last_name}`}</h1></div><button onClick={savePlayer} style={{...S.primary,background:theme.accent}}>Enregistrer</button></div><h3>Identité & administratif</h3><div style={S.formGrid}>{FIELDS1.map(([k,l,t])=><Edit key={k} k={k} label={l} type={t} draft={draft} setDraft={setDraft} theme={theme}/>)}</div><h3>Profil sportif</h3><div style={S.formGrid}>{FIELDS2.map(([k,l,t])=><Edit key={k} k={k} label={l} type={t} draft={draft} setDraft={setDraft} theme={theme}/>)}</div><label style={S.check}><input type='checkbox' checked={!!draft.promoted_age_group} onChange={e=>setDraft({...draft,promoted_age_group:e.target.checked})}/> Surclassé</label></>}</section></div>}
 {tab==='tests'&&<div style={S.grid2}><section style={{...S.card,background:theme.surface,borderColor:theme.border}}><h2>Nouveau résultat</h2><label>Joueur<select value={testPlayer} onChange={e=>setTestPlayer(e.target.value)} style={field(theme)}>{scoped.map(p=><option value={p.id} key={p.id}>{p.display_name||`${p.first_name} ${p.last_name}`}</option>)}</select></label><label>Test<select value={defId} onChange={e=>setDefId(e.target.value)} style={field(theme)}>{visibleDefs.map(d=><option value={d.id} key={d.id}>{d.name} · {d.unit}</option>)}</select></label>{defs.find(d=>d.id===defId)&&<div style={{...S.protocol,borderColor:theme.border}}><b>Protocole</b><span>{defs.find(d=>d.id===defId)?.protocol}</span><small style={{color:theme.muted}}>{defs.find(d=>d.id===defId)?.trial_count} essai(s) · meilleure valeur = {defs.find(d=>d.id===defId)?.best_rule}</small></div>}<label>Essais (séparés par des virgules)<input value={trials} onChange={e=>setTrials(e.target.value)} placeholder='43.1, 44.0, 43.7' style={field(theme)}/></label><label>Dispositif<input value={device} onChange={e=>setDevice(e.target.value)} placeholder='VALD, My Jump Lab, cellules…' style={field(theme)}/></label><label>Date / heure<input type='datetime-local' value={testedAt} onChange={e=>setTestedAt(e.target.value)} style={field(theme)}/></label><button onClick={saveTest} style={{...S.primary,background:theme.accent}}>Enregistrer le test</button></section><section style={{...S.card,background:theme.surface,borderColor:theme.border}}><h2>Protocoles actifs</h2>{visibleDefs.map(d=><div key={d.id} style={{...S.def,borderColor:theme.border}}><b>{d.name}</b><span>{d.protocol}</span><small style={{color:theme.muted}}>{d.unit} · {d.trial_count} essai(s)</small></div>)}</section></div>}
 {tab==='staff'&&<section style={{...S.card,background:theme.surface,borderColor:theme.border}}><h2>Staff & accès</h2><p style={{color:theme.muted}}>Les droits médicaux restent isolés via « accès médical ». Les autres permissions sont explicites.</p><div style={S.staffGrid}>{members.filter(m=>m.organization_id===org).map(m=>{const name=profiles.find(p=>p.user_id===m.user_id)?.full_name||m.user_id;const perms=m.permissions||{};return <article key={m.id} style={{...S.staffCard,background:theme.surface2,borderColor:theme.border}}><div><b>{name}</b><small style={{display:'block',color:theme.muted}}>{TEAMS.find(t=>t.id===m.team_id)?.name||'Toutes équipes'}</small></div><label>Rôle<select value={m.role||'staff'} onChange={e=>patchMember(m.id,{role:e.target.value})} style={field(theme)}>{ROLES.map(r=><option key={r}>{r}</option>)}</select></label><div style={S.perms}>{PERMS.map(p=><label key={p}><input type='checkbox' checked={!!perms[p]} onChange={e=>patchMember(m.id,{permissions:{...perms,[p]:e.target.checked}})}/>{p}</label>)}</div><label style={S.check}><input type='checkbox' checked={!!m.medical_clearance} onChange={e=>patchMember(m.id,{medical_clearance:e.target.checked})}/> Accès médical détaillé</label><label style={S.check}><input type='checkbox' checked={m.active!==false} onChange={e=>patchMember(m.id,{active:e.target.checked})}/> Compte actif</label></article>})}</div></section>}
 </section></main>
}

const FIELDS1:[string,string,string][]=[['first_name','Prénom','text'],['last_name','Nom','text'],['preferred_name','Nom usuel','text'],['sex','Sexe','text'],['birth_date','Date de naissance','date'],['birth_place','Lieu de naissance','text'],['nationalities','Nationalité(s)','text'],['license_number','N° licence','text'],['languages','Langues','text'],['phone','Téléphone','tel'],['email','Email','email'],['address','Adresse','text'],['city','Ville','text'],['country','Pays','text'],['dossier_status','Statut dossier','text']];
const FIELDS2:[string,string,string][]=[['category','Catégorie','text'],['season','Saison','text'],['jersey_number','N° maillot','number'],['primary_position','Poste principal','text'],['secondary_positions','Postes secondaires','text'],['dominant_foot','Pied dominant','text'],['weak_foot_level','Niveau pied faible','number'],['height_cm','Taille cm','number'],['weight_kg','Poids kg','number'],['wingspan_cm','Envergure cm','number'],['club_arrival_date','Arrivée au club','date'],['contract_type','Type contrat','text'],['contract_start_date','Début contrat','date'],['contract_end_date','Fin contrat','date'],['selections','Sélections','text'],['agent_name','Agent','text'],['agent_phone','Téléphone agent','text'],['agent_email','Email agent','email']];
function Edit({k,label,type,draft,setDraft,theme}:{k:string;label:string;type:string;draft:Row;setDraft:(x:Row)=>void;theme:any}){const isArr=['nationalities','languages','secondary_positions'].includes(k);const val=isArr?(Array.isArray(draft[k])?draft[k].join(', '):draft[k]||''):draft[k]??'';return <label>{label}<input type={type} value={val} onChange={e=>setDraft({...draft,[k]:e.target.value})} style={field(theme)}/></label>}
function arr(v:any){if(Array.isArray(v))return v;if(!v)return [];return String(v).split(',').map(x=>x.trim()).filter(Boolean)}
function field(t:any):React.CSSProperties{return {width:'100%',height:43,boxSizing:'border-box',marginTop:6,border:`1px solid ${t.border}`,borderRadius:10,padding:'0 10px',background:t.surface2,color:t.text}}
function tabStyle(active:boolean,t:any):React.CSSProperties{return {border:0,borderRadius:10,padding:'11px 14px',fontWeight:800,cursor:'pointer',background:active?t.accent:'transparent',color:active?'#fff':t.muted}}
const S:Record<string,React.CSSProperties>={center:{minHeight:'80vh',display:'grid',placeItems:'center'},header:{height:70,borderBottom:'1px solid',padding:'0 22px',display:'flex',gap:18,alignItems:'center',position:'sticky',top:0,zIndex:20},back:{textDecoration:'none',border:'1px solid',borderRadius:10,padding:'8px 11px'},wrap:{maxWidth:1400,margin:'0 auto',padding:24},switcher:{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(220px,300px))',gap:12,border:'1px solid',borderRadius:16,padding:14},tabs:{display:'flex',gap:7,border:'1px solid',borderRadius:14,padding:7,margin:'16px 0',overflowX:'auto'},notice:{border:'1px solid',borderRadius:12,padding:12,marginBottom:14},grid2:{display:'grid',gridTemplateColumns:'minmax(240px,330px) minmax(0,1fr)',gap:14},card:{border:'1px solid',borderRadius:18,padding:16,minWidth:0},cardHead:{display:'flex',justifyContent:'space-between',gap:12,alignItems:'center',flexWrap:'wrap'},person:{width:'100%',border:'1px solid',borderRadius:10,padding:10,marginBottom:6,textAlign:'left',display:'grid',gap:2,cursor:'pointer'},formGrid:{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(190px,1fr))',gap:11,marginBottom:18},primary:{border:0,color:'#fff',borderRadius:10,padding:'11px 15px',fontWeight:850,cursor:'pointer'},check:{display:'flex',gap:8,alignItems:'center',marginTop:10},protocol:{border:'1px solid',borderRadius:12,padding:12,display:'grid',gap:5,margin:'12px 0'},def:{borderBottom:'1px solid',padding:'10px 0',display:'grid',gap:4},staffGrid:{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(280px,1fr))',gap:10},staffCard:{border:'1px solid',borderRadius:14,padding:14,display:'grid',gap:10},perms:{display:'grid',gridTemplateColumns:'1fr 1fr',gap:7,fontSize:12}};