'use client';

import { useEffect,useMemo,useState } from 'react';
import { supabase } from '@/lib/supabase';

type Row=Record<string,any>;
const DIAMBARS='d3136b7f-ef28-43e8-af53-30fa6de70c62';
const ELITE='5454ad8f-8f2b-4812-9923-ab7d0b1f8748';
const TEAMS=[{id:'d9bb5390-94cb-461e-b2cd-a326da2cfa3d',name:'PRO A'},{id:'44f6976d-f5ef-4dcf-980f-ce3995e99877',name:'U19 · PRO B'},{id:'28b38b9f-3de0-419d-8275-b331a074b7f4',name:'U17'},{id:'e652df98-4653-416c-b794-3763e38a629d',name:'U15'}];

export default function Comparator(){
 const [ready,setReady]=useState(false),[ok,setOk]=useState(false),[org,setOrg]=useState(DIAMBARS),[team,setTeam]=useState(TEAMS[2].id),[players,setPlayers]=useState<Row[]>([]),[tests,setTests]=useState<Row[]>([]),[selected,setSelected]=useState<string[]>([]);
 useEffect(()=>{(async()=>{const {data:{session}}=await supabase.auth.getSession();if(!session){setReady(true);return}const [{data:p},{data:m}]=await Promise.all([supabase.from('profiles').select('is_super_admin').eq('user_id',session.user.id).maybeSingle(),supabase.from('memberships').select('id').eq('user_id',session.user.id).eq('active',true).limit(1)]);if(p?.is_super_admin||m?.length)setOk(true);setReady(true)})()},[]);
 useEffect(()=>{if(ok)load()},[ok,org,team]);
 async function load(){const q=org===DIAMBARS?supabase.from('players').select('id,display_name,first_name,last_name,primary_position,position').eq('organization_id',org).eq('team_id',team).eq('active',true):supabase.from('players').select('id,display_name,first_name,last_name,primary_position,position').eq('organization_id',org).eq('active',true);const {data:p}=await q;setPlayers(p||[]);const ids=(p||[]).map(x=>x.id);if(!ids.length){setTests([]);setSelected([]);return}const {data:t}=await supabase.from('test_results').select('*').eq('organization_id',org).in('player_id',ids).order('tested_at',{ascending:false}).limit(1000);setTests(t||[]);setSelected(v=>v.filter(id=>ids.includes(id)).slice(0,4))}
 function toggle(id:string){setSelected(v=>v.includes(id)?v.filter(x=>x!==id):(v.length<4?[...v,id]:v))}
 const metrics=useMemo(()=>{const names=new Set<string>();for(const t of tests.filter(x=>selected.includes(x.player_id)))names.add(String(t.test_name||t.name||t.test_definition_id||'Test'));return [...names].slice(0,20)},[tests,selected]);
 function latestValue(pid:string,metric:string){const t=tests.find(x=>x.player_id===pid&&String(x.test_name||x.name||x.test_definition_id||'Test')===metric);return t?.best_value??t?.mean_value??t?.value??'—'}
 if(!ready)return <main style={S.center}>Chargement…</main>;if(!ok)return <main style={S.center}>Accès staff requis.</main>;
 return <main style={S.main}><header style={S.header}><div><span style={S.kicker}>SPORT & PERFORMANCE</span><h1 style={S.h1}>Comparateur athlétique</h1><p style={S.sub}>Comparer jusqu’à 4 athlètes à partir des derniers résultats disponibles, sans mélanger des protocoles différents.</p></div><a href='/admin/sport' style={S.back}>← Sport & Performance</a></header>
 <section style={S.filters}><label>Organisation<select value={org} onChange={e=>setOrg(e.target.value)} style={S.input}><option value={DIAMBARS}>DIAMBARS FC</option><option value={ELITE}>HDY ELITE</option></select></label>{org===DIAMBARS&&<label>Équipe<select value={team} onChange={e=>setTeam(e.target.value)} style={S.input}>{TEAMS.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label>}<div style={S.count}>{selected.length}/4 athlètes</div></section>
 <section style={S.grid}><article style={S.card}><h2>Athlètes</h2>{players.map(p=><button key={p.id} onClick={()=>toggle(p.id)} style={{...S.player,background:selected.includes(p.id)?'#E31E24':'#1B1B1F'}}><span><b>{p.display_name||`${p.first_name} ${p.last_name}`}</b><small>{p.primary_position||p.position||'—'}</small></span><strong>{selected.includes(p.id)?'✓':'+'}</strong></button>)}</article>
 <article style={S.cardWide}><h2>Comparaison</h2>{!selected.length?<p style={S.sub}>Sélectionne 2 à 4 athlètes.</p>:<div style={S.tableWrap}><table style={S.table}><thead><tr><th>Test / protocole</th>{selected.map(id=><th key={id}>{nameOf(players,id)}</th>)}</tr></thead><tbody>{metrics.map(m=><tr key={m}><td><b>{m}</b></td>{selected.map(id=><td key={id}>{String(latestValue(id,m))}</td>)}</tr>)}</tbody></table></div>}<p style={S.note}>Lecture descriptive uniquement. Une valeur n’est comparable que si le protocole, le dispositif et les conditions de test sont cohérents.</p></article></section></main>
}
function nameOf(players:Row[],id:string){const p=players.find(x=>x.id===id);return p?.display_name||`${p?.first_name||''} ${p?.last_name||''}`.trim()||'Athlète'}
const S:Record<string,React.CSSProperties>={center:{minHeight:'80vh',display:'grid',placeItems:'center',fontFamily:'system-ui'},main:{minHeight:'100vh',background:'#09090B',color:'#FAFAFA',fontFamily:'Inter,system-ui,sans-serif',padding:28},header:{maxWidth:1280,margin:'0 auto 18px',display:'flex',justifyContent:'space-between',gap:20},kicker:{fontSize:11,fontWeight:900,letterSpacing:1.5,color:'#E31E24'},h1:{fontSize:'clamp(38px,5vw,64px)',margin:'4px 0',letterSpacing:-2.5},sub:{color:'#A1A1AA',maxWidth:720},back:{color:'#fff',textDecoration:'none',border:'1px solid #2B2B31',borderRadius:10,padding:'10px 12px',height:'fit-content'},filters:{maxWidth:1280,margin:'0 auto 14px',display:'flex',gap:12,alignItems:'end',flexWrap:'wrap',background:'#141416',border:'1px solid #2B2B31',borderRadius:16,padding:14},input:{display:'block',minWidth:220,height:42,marginTop:6,background:'#1B1B1F',color:'#fff',border:'1px solid #34343A',borderRadius:10,padding:'0 10px'},count:{marginLeft:'auto',fontWeight:900},grid:{maxWidth:1280,margin:'0 auto',display:'grid',gridTemplateColumns:'320px 1fr',gap:14},card:{background:'#141416',border:'1px solid #2B2B31',borderRadius:18,padding:16},cardWide:{background:'#141416',border:'1px solid #2B2B31',borderRadius:18,padding:16,overflow:'hidden'},player:{width:'100%',border:'1px solid #2B2B31',color:'#fff',borderRadius:10,padding:'10px 12px',marginBottom:8,display:'flex',justifyContent:'space-between',alignItems:'center',textAlign:'left'},tableWrap:{overflowX:'auto'},table:{width:'100%',borderCollapse:'collapse',fontSize:13},note:{marginTop:14,color:'#A1A1AA',fontSize:12}};