'use client';

import {useEffect,useMemo,useState} from 'react';
import {useParams} from 'next/navigation';
import {supabase} from '@/lib/supabase';

type Row=Record<string,any>;
const ACWR_WATCH=1.30;
const ACWR_HIGH=1.50;
function n(v:any){const x=Number(v);return Number.isFinite(x)?x:null}
function pct(vals:number[],p:number){if(!vals.length)return null;const a=[...vals].sort((x,y)=>x-y);const i=Math.min(a.length-1,Math.max(0,Math.ceil(p*a.length)-1));return a[i]}
function show(v:any,d=2){const x=n(v);return x===null?'—':x.toFixed(d)}
function acwrLevel(v:any){const x=n(v);if(x===null)return null;if(x>=ACWR_HIGH)return 'red';if(x>=ACWR_WATCH)return 'orange';return 'green'}

export default function PlayerDossier(){
 const params=useParams<{id:string}>(); const id=params?.id;
 const [ready,setReady]=useState(false),[ok,setOk]=useState(false),[player,setPlayer]=useState<Row|null>(null),[gps,setGps]=useState<Row[]>([]),[q,setQ]=useState<Row[]>([]),[rpe,setRpe]=useState<Row[]>([]),[pain,setPain]=useState<Row[]>([]),[alerts,setAlerts]=useState<Row[]>([]);
 useEffect(()=>{if(!id)return;(async()=>{const {data:{session}}=await supabase.auth.getSession();if(!session){setReady(true);return}const [{data:prof},{data:mem}]=await Promise.all([supabase.from('profiles').select('is_super_admin').eq('user_id',session.user.id).maybeSingle(),supabase.from('memberships').select('id').eq('user_id',session.user.id).eq('active',true).limit(1)]);if(!prof?.is_super_admin&&!mem?.length){setReady(true);return}setOk(true);const {data:p}=await supabase.from('players').select('id,display_name,first_name,last_name,primary_position,position,status,photo_url,organization_id,team_id').eq('id',id).maybeSingle();setPlayer(p);if(p){const [g,qq,rr,pp,aa]=await Promise.all([supabase.from('gps_records').select('id,metrics,provider,source,recorded_at').eq('player_id',id).order('recorded_at',{ascending:false}).limit(500),supabase.from('questionnaire_responses').select('answers,submitted_at').eq('player_id',id).order('submitted_at',{ascending:false}).limit(300),supabase.from('session_rpe').select('rpe,load_ua,actual_duration_min,submitted_at').eq('player_id',id).order('submitted_at',{ascending:false}).limit(300),supabase.from('pain_declarations').select('*').eq('player_id',id).order('created_at',{ascending:false}).limit(300),supabase.from('alerts').select('*').eq('player_id',id).order('created_at',{ascending:false}).limit(100)]);setGps((g.data||[]) as Row[]);setQ((qq.data||[]) as Row[]);setRpe((rr.data||[]) as Row[]);setPain((pp.data||[]) as Row[]);setAlerts((aa.data||[]) as Row[])}setReady(true)})()},[id]);
 const hist=useMemo(()=>gps.filter(x=>x.source==='xlsx_historical'),[gps]);
 const base=useMemo(()=>{const val=(k:string)=>hist.map(x=>n(x.metrics?.[k])).filter((x):x is number=>x!==null);return {sessions:hist.length,vmax:Math.max(0,...val('max_speed_kmh')),distanceP90:pct(val('total_distance_km'),.9),hidP90:pct(val('high_intensity_distance_km'),.9),sprintP90:pct(val('sprint_distance_km'),.9),extP90:pct(val('external_load'),.9),sprintCountP90:pct(val('sprint_count'),.9),maxAcwr:Math.max(0,...val('acwr'))}} ,[hist]);
 const latest=gps[0], latestM=latest?.metrics||{}; const latestQ=q[0]?.answers||{}; const latestR=rpe[0]; const latestPain=pain[0]; const activeAlert=alerts.find(a=>a.status!=='closed'); const currentLevel=activeAlert?.level||acwrLevel(latestM.acwr);
 if(!ready)return <main style={S.center}>Chargement…</main>; if(!ok)return <main style={S.center}>Accès staff requis.</main>; if(!player)return <main style={S.center}>Joueur introuvable.</main>;
 const name=player.display_name||`${player.first_name} ${player.last_name}`;
 return <main style={S.main}><header style={S.header}><div><span style={S.kicker}>DOSSIER LONGITUDINAL · STAFF</span><h1 style={S.h1}>{name}</h1><p style={S.sub}>{player.primary_position||player.position||'Joueur'} · {player.status||'—'} · GPS, charge, ressentis et alertes avec provenance tracée</p></div><a href='/admin/sport/monitoring' style={S.back}>← Monitoring</a></header>
 {currentLevel&&currentLevel!=='green'&&<section style={{...S.alert,borderColor:currentLevel==='red'?'#B91C1C':'#A16207',background:currentLevel==='red'?'#2A1114':'#241D0D'}}><div><span style={S.alertBadge}>{currentLevel==='red'?'ALERTE STAFF MÉDICAL / PERFORMANCE':'VIGILANCE CHARGE'}</span><h2 style={{margin:'8px 0 4px'}}>{activeAlert?.reason||`ACWR ${show(latestM.acwr)} — revue staff recommandée`}</h2><p style={S.note}>Signal automatique de revue. Il ne constitue ni un diagnostic ni une décision d’exclusion.</p></div><a href='/admin/sport/alerts' style={S.alertLink}>Gérer les alertes →</a></section>}
 <section style={S.grid}><K title='Historique GPS' value={`${base.sessions}`} unit='séances'/><K title='Vmax historique' value={show(base.vmax)} unit='km/h'/><K title='P90 distance' value={show(base.distanceP90)} unit='km'/><K title='P90 haute intensité' value={show(base.hidP90)} unit='km'/><K title='P90 sprint' value={show(base.sprintP90)} unit='km'/><K title='P90 charge externe' value={show(base.extP90,0)} unit='index'/><K title='ACWR historique max' value={show(base.maxAcwr)} unit='ratio'/></section>
 <section style={S.card}><h2>Lecture du jour / dernière donnée</h2><div style={S.grid}><K title='Distance' value={show(latestM.total_distance_km??(n(latestM.total_distance_m)!/1000))} unit='km'/><K title='HID / HSR' value={show(latestM.high_intensity_distance_km??(n(latestM.high_speed_distance_m)!/1000))} unit='km'/><K title='Sprint' value={show(latestM.sprint_distance_km??(n(latestM.sprint_distance_m)!/1000))} unit='km'/><K title='Sprints' value={show(latestM.sprint_count,0)} unit='nb'/><K title='Vmax' value={show(latestM.max_speed_kmh)} unit='km/h'/><K title='Charge externe' value={show(latestM.external_load,0)} unit='index'/><K title='Charge aiguë 7j' value={show(latestM.acute_load_7d,0)} unit='charge'/><K title='Charge chronique 28j' value={show(latestM.chronic_load_28d,0)} unit='charge hebdo'/><K title='ACWR' value={show(latestM.acwr)} unit={acwrLevel(latestM.acwr)==='red'?'ALERTE':acwrLevel(latestM.acwr)==='orange'?'VIGILANCE':'ratio'}/></div><p style={S.note}>Source GPS : {latest?.provider||'—'} · {latest?.source||'—'} · {latest?.recorded_at?new Date(latest.recorded_at).toLocaleDateString('fr-FR'):'—'}</p></section>
 <section style={S.two}><article style={S.card}><h2>Ressenti joueur</h2><p>Hooper : <b>{latestQ.hooper_total??'—'} / 28</b></p><p>RPE déclaré dans l’app : <b>{latestR?.rpe??'—'}</b></p><p>sRPE : <b>{latestR?.load_ua??'—'}</b></p><p>Douleur déclarée : <b>{latestPain?.intensity??latestPain?.pain_intensity??'—'} / 10</b></p><p style={S.note}>Le RPE historique du classeur reste dans la donnée GPS avec sa provenance ; il n’est pas confondu avec le RPE déclaré par le joueur dans l’application.</p></article><article style={S.card}><h2>Comparaison au profil historique</h2><Ratio label='Distance / P90' value={n(latestM.total_distance_km)} ref={base.distanceP90}/><Ratio label='HID / P90' value={n(latestM.high_intensity_distance_km)} ref={base.hidP90}/><Ratio label='Sprint / P90' value={n(latestM.sprint_distance_km)} ref={base.sprintP90}/><Ratio label='Charge externe / P90' value={n(latestM.external_load)} ref={base.extP90}/><p style={S.note}>Les dépassements et l’ACWR sont des signaux de contexte destinés à déclencher une revue staff. La validation médicale reste humaine.</p></article></section>
 <section style={S.card}><h2>Historique GPS & charge</h2><div style={S.tableWrap}><table style={S.table}><thead><tr><th>Date</th><th>Contexte</th><th>Dist. km</th><th>HID km</th><th>Sprint km</th><th>Sprints</th><th>Vmax</th><th>Ext.</th><th>Aiguë 7j</th><th>Chronique 28j</th><th>ACWR</th><th>Signal</th><th>Provenance</th></tr></thead><tbody>{gps.slice(0,150).map(x=>{const m=x.metrics||{},level=acwrLevel(m.acwr);return <tr key={x.id}><td>{new Date(x.recorded_at).toLocaleDateString('fr-FR')}</td><td>{m.theme||m.session_type||'—'}</td><td>{show(m.total_distance_km??(n(m.total_distance_m)!/1000))}</td><td>{show(m.high_intensity_distance_km??(n(m.high_speed_distance_m)!/1000))}</td><td>{show(m.sprint_distance_km??(n(m.sprint_distance_m)!/1000))}</td><td>{show(m.sprint_count,0)}</td><td>{show(m.max_speed_kmh)}</td><td>{show(m.external_load,0)}</td><td>{show(m.acute_load_7d,0)}</td><td>{show(m.chronic_load_28d,0)}</td><td>{show(m.acwr)}</td><td>{level&&level!=='green'?<span style={{...S.signal,background:level==='red'?'#7F1D1D':'#713F12'}}>{level==='red'?'ALERTE':'VIGILANCE'}</span>:'—'}</td><td>{x.source}</td></tr>})}</tbody></table></div></section>
 </main>}
function K({title,value,unit}:{title:string,value:string,unit:string}){return <article style={S.kpi}><small>{title}</small><strong>{value}</strong><span>{unit}</span></article>}
function Ratio({label,value,ref}:{label:string,value:number|null,ref:number|null}){const r=value!==null&&ref?value/ref:null;return <div style={S.ratio}><span>{label}</span><b>{r===null?'—':`${Math.round(r*100)} %`}</b></div>}
const S:Record<string,React.CSSProperties>={center:{minHeight:'80vh',display:'grid',placeItems:'center',fontFamily:'system-ui'},main:{minHeight:'100vh',background:'#09090B',color:'#FAFAFA',fontFamily:'Inter,system-ui,sans-serif',padding:28},header:{maxWidth:1280,margin:'0 auto 18px',display:'flex',justifyContent:'space-between',gap:20,flexWrap:'wrap'},kicker:{fontSize:11,fontWeight:900,letterSpacing:1.5,color:'#E31E24'},h1:{fontSize:'clamp(38px,5vw,64px)',margin:'4px 0',letterSpacing:-2.5},sub:{color:'#A1A1AA'},back:{color:'#fff',textDecoration:'none',border:'1px solid #2B2B31',borderRadius:10,padding:'10px 12px',height:'fit-content'},alert:{maxWidth:1280,margin:'0 auto 14px',border:'1px solid',borderRadius:16,padding:16,display:'flex',justifyContent:'space-between',gap:16,alignItems:'center',flexWrap:'wrap'},alertBadge:{fontSize:10,fontWeight:900,letterSpacing:.8},alertLink:{background:'#fff',color:'#111',textDecoration:'none',padding:'10px 12px',borderRadius:9,fontWeight:850},grid:{maxWidth:1280,margin:'0 auto 14px',display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(155px,1fr))',gap:10},kpi:{background:'#141416',border:'1px solid #2B2B31',borderRadius:15,padding:14,display:'grid',gap:4},card:{maxWidth:1280,margin:'0 auto 14px',background:'#141416',border:'1px solid #2B2B31',borderRadius:18,padding:16},two:{maxWidth:1280,margin:'0 auto',display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(320px,1fr))',gap:14},note:{color:'#A1A1AA',fontSize:12},ratio:{display:'flex',justifyContent:'space-between',padding:'10px 0',borderBottom:'1px solid #2B2B31'},tableWrap:{overflowX:'auto'},table:{width:'100%',borderCollapse:'collapse',fontSize:12},signal:{display:'inline-block',padding:'4px 7px',borderRadius:999,fontSize:10,fontWeight:900,color:'#fff'}}