'use client';

import { useEffect, useMemo, useState } from 'react';
import { supabase } from '@/lib/supabase';
import { useOrg } from '@/lib/org-context';

type Row=Record<string,any>;
function SessionProgram({session,onClose}:{session:Row;onClose:()=>void}){
 const [exercises,setExercises]=useState<Row[]>([]),[content,setContent]=useState<Row[]>([]),[exerciseId,setExerciseId]=useState(''),[sets,setSets]=useState(3),[reps,setReps]=useState('10'),[rest,setRest]=useState(60),[loadNote,setLoadNote]=useState(''),[notes,setNotes]=useState(''),[msg,setMsg]=useState('');
 async function load(){const [{data:ex},{data:se}]=await Promise.all([supabase.from('exercises').select('*').eq('organization_id',session.organization_id).eq('active',true).order('name'),supabase.from('session_exercises').select('*, exercise:exercises(name,category)').eq('session_id',session.id).order('position')]);setExercises(ex||[]);setContent(se||[]);if(!exerciseId&&ex?.length)setExerciseId(ex[0].id)}
 useEffect(()=>{load()},[session.id]);
 async function add(){if(!exerciseId){setMsg('Choisis un exercice.');return}const {error}=await supabase.from('session_exercises').insert({organization_id:session.organization_id,session_id:session.id,exercise_id:exerciseId,position:content.length,sets:sets||null,reps:reps||null,rest_seconds:rest||null,load_note:loadNote||null,notes:notes||null});setMsg(error?error.message:'Exercice ajouté à la séance ✓');if(!error){setLoadNote('');setNotes('');await load()}}
 async function remove(id:string){const {error}=await supabase.from('session_exercises').delete().eq('id',id);if(!error)await load()}
 return <div style={S.overlay} onClick={onClose}><div style={S.modal} onClick={e=>e.stopPropagation()}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><h2>Contenu · {session.title||session.type} · {session.session_date}</h2><button onClick={onClose} style={S.smallGhost}>Fermer</button></div>{msg&&<div style={S.notice}>{msg}</div>}<div style={S.programGrid}><div style={S.card}><h3>Ajouter un exercice</h3><label>Exercice<select value={exerciseId} onChange={e=>setExerciseId(e.target.value)} style={S.input}>{exercises.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><div style={S.twoCol}><label>Séries<input type='number' value={sets} onChange={e=>setSets(Number(e.target.value))} style={S.input}/></label><label>Répétitions<input value={reps} onChange={e=>setReps(e.target.value)} style={S.input} placeholder="10 ou 30s"/></label></div><div style={S.twoCol}><label>Récup. (s)<input type='number' value={rest} onChange={e=>setRest(Number(e.target.value))} style={S.input}/></label><label>Charge<input value={loadNote} onChange={e=>setLoadNote(e.target.value)} style={S.input} placeholder="ex. 60% 1RM"/></label></div><label>Notes<input value={notes} onChange={e=>setNotes(e.target.value)} style={S.input}/></label><button onClick={add} style={S.primary}>Ajouter à la séance</button>{!exercises.length&&<small>Aucun exercice actif dans la <a href='/admin/sport/exercises' style={{color:'#fff'}}>banque d'exercices</a>.</small>}</div><div style={S.card}><h3>Programme de la séance ({content.length})</h3>{content.map((c,i)=><div key={c.id} style={S.row}><span><b>{i+1}. {c.exercise?.name||'—'}</b><small>{c.sets?`${c.sets}×${c.reps||'—'}`:c.reps||''}{c.rest_seconds?` · récup ${c.rest_seconds}s`:''}{c.load_note?` · ${c.load_note}`:''}</small></span><button onClick={()=>remove(c.id)} style={S.smallGhost}>Retirer</button></div>)}{!content.length&&<p style={{color:'#A1A1AA'}}>Aucun exercice prescrit pour l'instant.</p>}</div></div></div></div>
}
export default function SessionsPage(){
 const {environments,currentEnvId:org,setCurrentEnvId:setOrg,currentTeamId:team,setCurrentTeamId:setTeam,teamsFor,usesTeams}=useOrg();
 const [ready,setReady]=useState(false),[ok,setOk]=useState(false),[sessions,setSessions]=useState<Row[]>([]),[title,setTitle]=useState('Entraînement collectif'),[type,setType]=useState('training'),[date,setDate]=useState(new Date().toISOString().slice(0,10)),[duration,setDuration]=useState(75),[plannedRpe,setPlannedRpe]=useState(6),[location,setLocation]=useState(''),[msg,setMsg]=useState(''),[programFor,setProgramFor]=useState<Row|null>(null);
 async function load(){const {data}=await supabase.from('sessions').select('*').order('session_date',{ascending:false}).limit(100);setSessions(data||[])}
 useEffect(()=>{(async()=>{const {data:{session}}=await supabase.auth.getSession();if(!session){setReady(true);return}const [{data:p},{data:m}]=await Promise.all([supabase.from('profiles').select('is_super_admin').eq('user_id',session.user.id).maybeSingle(),supabase.from('memberships').select('id').eq('user_id',session.user.id).eq('active',true).limit(1)]);if(!p?.is_super_admin&&!m?.length){setReady(true);return}setOk(true);await load();setReady(true)})()},[]);
 const scoped=useMemo(()=>sessions.filter(s=>s.organization_id===org&&(!usesTeams(org)||!team||s.team_id===team)),[sessions,org,team,usesTeams]);
 async function save(){if(!date){setMsg('Date requise.');return}if(usesTeams(org)&&!team){setMsg('Sélectionne une équipe.');return}const {error}=await supabase.from('sessions').insert({organization_id:org,team_id:usesTeams(org)?team:null,type,title:title||null,session_date:date,planned_duration_min:duration||null,planned_rpe:plannedRpe||null,location:location||null,metadata:{source:'staff_web'}});setMsg(error?error.message:'Séance créée ✓');if(!error)await load()}
 if(!ready)return <main style={S.center}>Chargement…</main>;if(!ok)return <main style={S.center}>Accès staff requis.</main>;
 return <main style={S.main}><header style={S.header}><div><span style={S.kicker}>SPORT & PERFORMANCE</span><h1>Séances</h1><p>Création, planification et contenu (exercices) des séances utilisées ensuite pour le RPE Foster.</p></div><a href='/admin/sport' style={S.back}>← Sport & Performance</a></header><section style={S.toolbar}><label>Environnement<select value={org} onChange={e=>setOrg(e.target.value)} style={S.input}>{environments.map(e=><option key={e.id} value={e.id}>{e.branding?.label||e.name}</option>)}</select></label>{usesTeams(org)&&<label>Équipe<select value={team} onChange={e=>setTeam(e.target.value)} style={S.input}><option value=''>— sélectionner —</option>{teamsFor(org).map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label>}</section>{msg&&<div style={S.notice}>{msg}</div>}<section style={S.grid}><article style={S.card}><h2>Nouvelle séance</h2><label>Titre<input value={title} onChange={e=>setTitle(e.target.value)} style={S.input}/></label><label>Type<select value={type} onChange={e=>setType(e.target.value)} style={S.input}><option value='training'>Entraînement</option><option value='match'>Match</option><option value='gym'>Musculation</option><option value='rehab'>Réathlétisation</option><option value='recovery'>Récupération</option><option value='test'>Tests</option></select></label><label>Date<input type='date' value={date} onChange={e=>setDate(e.target.value)} style={S.input}/></label><label>Lieu<input value={location} onChange={e=>setLocation(e.target.value)} style={S.input} placeholder='Terrain principal…'/></label><label>Durée prévue (min)<input type='number' value={duration} onChange={e=>setDuration(Number(e.target.value))} style={S.input}/></label><label>RPE prévu<input type='number' min={1} max={10} value={plannedRpe} onChange={e=>setPlannedRpe(Number(e.target.value))} style={S.input}/></label><div style={S.load}>Charge prévisionnelle <b>{duration*plannedRpe} UA</b></div><button onClick={save} style={S.primary}>Créer la séance</button></article><article style={S.card}><h2>Séances récentes</h2>{scoped.slice(0,30).map(s=><div key={s.id} style={S.row}><span><b>{s.title||s.type}</b><small>{s.session_date} · {s.type}{s.location?` · ${s.location}`:''}</small></span><span style={{display:'flex',alignItems:'center',gap:10}}><strong>{s.planned_duration_min||'—'} min · RPE {s.planned_rpe||'—'}</strong><button onClick={()=>setProgramFor(s)} style={S.smallGhost}>Programme</button></span></div>)}</article></section>{programFor&&<SessionProgram session={programFor} onClose={()=>setProgramFor(null)}/>}</main>
}
const S:Record<string,React.CSSProperties>={center:{minHeight:'80vh',display:'grid',placeItems:'center'},main:{minHeight:'100vh',background:'#09090B',color:'#FAFAFA',fontFamily:'Inter,system-ui,sans-serif',padding:28},header:{maxWidth:1200,margin:'0 auto 20px',display:'flex',justifyContent:'space-between',gap:20},kicker:{fontSize:11,fontWeight:900,letterSpacing:1.4,color:'#E31E24'},back:{color:'#fff',textDecoration:'none',border:'1px solid #2B2B31',padding:'10px 12px',borderRadius:10,height:'fit-content'},toolbar:{maxWidth:1200,margin:'0 auto 16px',background:'#141416',border:'1px solid #2B2B31',borderRadius:16,padding:14,display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(220px,1fr))',gap:12},input:{width:'100%',height:42,background:'#1B1B1F',color:'#fff',border:'1px solid #2B2B31',borderRadius:10,padding:'0 10px',marginTop:6,boxSizing:'border-box'},notice:{maxWidth:1200,margin:'0 auto 14px',background:'#141416',border:'1px solid #2B2B31',borderRadius:12,padding:12},grid:{maxWidth:1200,margin:'0 auto',display:'grid',gridTemplateColumns:'minmax(280px,.8fr) minmax(0,1.2fr)',gap:14},card:{background:'#141416',border:'1px solid #2B2B31',borderRadius:16,padding:16,display:'grid',gap:12,alignContent:'start'},primary:{border:0,borderRadius:10,padding:'12px 15px',fontWeight:850,color:'#fff',background:'#E31E24',cursor:'pointer'},row:{display:'flex',justifyContent:'space-between',gap:10,padding:'10px 0',borderBottom:'1px solid #2B2B31',alignItems:'center'},load:{background:'#1B1B1F',border:'1px solid #2B2B31',borderRadius:12,padding:12,display:'flex',justifyContent:'space-between'},smallGhost:{border:'1px solid #2B2B31',borderRadius:8,padding:'6px 10px',fontWeight:700,color:'#fff',background:'transparent',cursor:'pointer',fontSize:12},overlay:{position:'fixed',inset:0,background:'rgba(0,0,0,.7)',display:'grid',placeItems:'center',padding:20,zIndex:50},modal:{background:'#0D0D0F',border:'1px solid #2B2B31',borderRadius:18,padding:20,maxWidth:900,width:'100%',maxHeight:'88vh',overflowY:'auto',display:'grid',gap:14},programGrid:{display:'grid',gridTemplateColumns:'minmax(260px,.9fr) minmax(0,1.1fr)',gap:14},twoCol:{display:'grid',gridTemplateColumns:'1fr 1fr',gap:10}};