'use client';

import { useEffect, useMemo, useState } from 'react';
import { supabase } from '@/lib/supabase';

type Row=Record<string,any>;
const DIAMBARS='d3136b7f-ef28-43e8-af53-30fa6de70c62';
const ELITE='5454ad8f-8f2b-4812-9923-ab7d0b1f8748';
const TEAMS=[{id:'d9bb5390-94cb-461e-b2cd-a326da2cfa3d',name:'PRO A'},{id:'44f6976d-f5ef-4dcf-980f-ce3995e99877',name:'U19 · PRO B'},{id:'28b38b9f-3de0-419d-8275-b331a074b7f4',name:'U17'},{id:'e652df98-4653-416c-b794-3763e38a629d',name:'U15'}];
export default function SessionsPage(){
 const [ready,setReady]=useState(false),[ok,setOk]=useState(false),[org,setOrg]=useState(DIAMBARS),[team,setTeam]=useState(TEAMS[2].id),[sessions,setSessions]=useState<Row[]>([]),[title,setTitle]=useState('Entraînement collectif'),[type,setType]=useState('training'),[date,setDate]=useState(new Date().toISOString().slice(0,10)),[duration,setDuration]=useState(75),[plannedRpe,setPlannedRpe]=useState(6),[msg,setMsg]=useState('');
 async function load(){const {data}=await supabase.from('sessions').select('*').order('session_date',{ascending:false}).limit(100);setSessions(data||[])}
 useEffect(()=>{(async()=>{const {data:{session}}=await supabase.auth.getSession();if(!session){setReady(true);return}const {data}=await supabase.from('profiles').select('is_super_admin').eq('user_id',session.user.id).maybeSingle();if(!data?.is_super_admin){setReady(true);return}setOk(true);await load();setReady(true)})()},[]);
 const scoped=useMemo(()=>sessions.filter(s=>s.organization_id===org&&(org!==DIAMBARS||s.team_id===team)),[sessions,org,team]);
 async function save(){if(!date){setMsg('Date requise.');return}const {error}=await supabase.from('sessions').insert({organization_id:org,team_id:org===DIAMBARS?team:null,type,title:title||null,session_date:date,planned_duration_min:duration||null,planned_rpe:plannedRpe||null,metadata:{source:'staff_web'}});setMsg(error?error.message:'Séance créée ✓');if(!error)await load()}
 if(!ready)return <main style={S.center}>Chargement…</main>;if(!ok)return <main style={S.center}>Accès administrateur principal requis.</main>;
 return <main style={S.main}><header style={S.header}><div><span style={S.kicker}>SPORT & PERFORMANCE</span><h1>Séances</h1><p>Création et planification des séances utilisées ensuite pour le RPE Foster.</p></div><a href='/admin/sport' style={S.back}>← Sport & Performance</a></header><section style={S.toolbar}><label>Organisation<select value={org} onChange={e=>setOrg(e.target.value)} style={S.input}><option value={DIAMBARS}>DIAMBARS FC</option><option value={ELITE}>HDY ELITE</option></select></label>{org===DIAMBARS&&<label>Équipe<select value={team} onChange={e=>setTeam(e.target.value)} style={S.input}>{TEAMS.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label>}</section>{msg&&<div style={S.notice}>{msg}</div>}<section style={S.grid}><article style={S.card}><h2>Nouvelle séance</h2><label>Titre<input value={title} onChange={e=>setTitle(e.target.value)} style={S.input}/></label><label>Type<select value={type} onChange={e=>setType(e.target.value)} style={S.input}><option value='training'>Entraînement</option><option value='match'>Match</option><option value='gym'>Musculation</option><option value='rehab'>Réathlétisation</option><option value='recovery'>Récupération</option><option value='test'>Tests</option></select></label><label>Date<input type='date' value={date} onChange={e=>setDate(e.target.value)} style={S.input}/></label><label>Durée prévue (min)<input type='number' value={duration} onChange={e=>setDuration(Number(e.target.value))} style={S.input}/></label><label>RPE prévu<input type='number' min={1} max={10} value={plannedRpe} onChange={e=>setPlannedRpe(Number(e.target.value))} style={S.input}/></label><div style={S.load}>Charge prévisionnelle <b>{duration*plannedRpe} UA</b></div><button onClick={save} style={S.primary}>Créer la séance</button></article><article style={S.card}><h2>Séances récentes</h2>{scoped.slice(0,30).map(s=><div key={s.id} style={S.row}><span><b>{s.title||s.type}</b><small>{s.session_date} · {s.type}</small></span><strong>{s.planned_duration_min||'—'} min · RPE {s.planned_rpe||'—'}</strong></div>)}</article></section></main>
}
const S:Record<string,React.CSSProperties>={center:{minHeight:'80vh',display:'grid',placeItems:'center'},main:{minHeight:'100vh',background:'#09090B',color:'#FAFAFA',fontFamily:'Inter,system-ui,sans-serif',padding:28},header:{maxWidth:1200,margin:'0 auto 20px',display:'flex',justifyContent:'space-between',gap:20},kicker:{fontSize:11,fontWeight:900,letterSpacing:1.4,color:'#E31E24'},back:{color:'#fff',textDecoration:'none',border:'1px solid #2B2B31',padding:'10px 12px',borderRadius:10,height:'fit-content'},toolbar:{maxWidth:1200,margin:'0 auto 16px',background:'#141416',border:'1px solid #2B2B31',borderRadius:16,padding:14,display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(220px,1fr))',gap:12},input:{width:'100%',height:42,background:'#1B1B1F',color:'#fff',border:'1px solid #2B2B31',borderRadius:10,padding:'0 10px',marginTop:6,boxSizing:'border-box'},notice:{maxWidth:1200,margin:'0 auto 14px',background:'#141416',border:'1px solid #2B2B31',borderRadius:12,padding:12},grid:{maxWidth:1200,margin:'0 auto',display:'grid',gridTemplateColumns:'minmax(280px,.8fr) minmax(0,1.2fr)',gap:14},card:{background:'#141416',border:'1px solid #2B2B31',borderRadius:16,padding:16,display:'grid',gap:12},primary:{border:0,borderRadius:10,padding:'12px 15px',fontWeight:850,color:'#fff',background:'#E31E24',cursor:'pointer'},row:{display:'flex',justifyContent:'space-between',gap:10,padding:'10px 0',borderBottom:'1px solid #2B2B31'},load:{background:'#1B1B1F',border:'1px solid #2B2B31',borderRadius:12,padding:12,display:'flex',justifyContent:'space-between'}};