'use client';

export default function Sport(){
 const cards=[
  {href:'/admin/sport/tests',title:'Tests & évaluations',desc:'Saisie des résultats, protocoles actifs et suivi des performances.'},
  {href:'/admin/sport/sessions',title:'Séances',desc:'Créer les séances d’équipe et préparer le suivi RPE associé.'},
  {href:'/admin/sport/hrv',title:'HDY ELITE · HRV',desc:'Importer un CSV HRV et croiser les mesures avec Hooper, RPE et sRPE au quotidien.'},
  {href:'/admin/workspace',title:'Monitoring',desc:'Hooper, RPE Foster, douleurs et pilotage quotidien des équipes.'},
  {href:'/admin/workspace',title:'Comparateur',desc:'Comparer les profils athlétiques avec lecture descriptive et protocole cohérent.'},
 ];
 return <main style={S.main}><header style={S.header}><div><span style={S.kicker}>HDY PERFORMANCE ENGINE</span><h1 style={S.h1}>Sport & Performance</h1><p style={S.p}>Séances, tests, monitoring et analyse. Les fonctions administratives sont séparées.</p></div><a href='/admin' style={S.back}>← Portail</a></header><section style={S.grid}>{cards.map(c=><a key={c.title} href={c.href} style={S.card}><span style={S.badge}>PERFORMANCE</span><h2>{c.title}</h2><p>{c.desc}</p><b>Ouvrir →</b></a>)}</section><section style={S.split}><div><h2>Sport & Performance</h2><p>Aucune donnée administrative sensible n’est mélangée dans cet espace.</p></div><a href='/admin/administration' style={S.admin}>Accéder à Administration →</a></section></main>
}
const S:Record<string,React.CSSProperties>={main:{minHeight:'100vh',background:'#09090B',color:'#FAFAFA',fontFamily:'Inter,system-ui,sans-serif',padding:28},header:{maxWidth:1180,margin:'0 auto 24px',display:'flex',justifyContent:'space-between',gap:20,alignItems:'flex-start'},kicker:{fontSize:11,letterSpacing:1.5,fontWeight:900,color:'#E31E24'},h1:{fontSize:'clamp(40px,6vw,72px)',margin:'4px 0 8px',letterSpacing:-3},p:{color:'#A1A1AA',maxWidth:650},back:{color:'#fff',textDecoration:'none',border:'1px solid #2B2B31',padding:'10px 12px',borderRadius:10},grid:{maxWidth:1180,margin:'0 auto',display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(250px,1fr))',gap:14},card:{background:'#141416',border:'1px solid #2B2B31',borderRadius:18,padding:20,color:'#fff',textDecoration:'none',display:'grid',gap:10},badge:{fontSize:10,fontWeight:900,color:'#E31E24'},split:{maxWidth:1180,margin:'20px auto 0',background:'#141416',border:'1px solid #2B2B31',borderRadius:18,padding:20,display:'flex',justifyContent:'space-between',gap:16,alignItems:'center',flexWrap:'wrap'},admin:{background:'#fff',color:'#111',textDecoration:'none',borderRadius:10,padding:'12px 16px',fontWeight:850}};