'use client';

export default function Sport(){
 const cards=[
  {href:'/admin/sport/tests',title:'Tests & évaluations',desc:'Saisie des résultats, protocoles actifs et suivi des performances.'},
  {href:'/admin/sport/sessions',title:'Séances',desc:'Créer les séances d’équipe et préparer le suivi RPE associé.'},
  {href:'/admin/sport/gps',title:'GPS · Charge externe',desc:'Importer CSV ou Excel/Numbers, calculer la charge et alimenter le suivi longitudinal.'},
  {href:'/admin/sport/alerts',title:'Alertes médicales & performance',desc:'Signaux automatiques ACWR à revoir par le staff, avec acquittement et clôture tracés.'},
  {href:'/admin/sport/hrv',title:'HRV · récupération',desc:'Mesures HRV pour les organisations et joueurs pour lesquels ce suivi est activé.'},
  {href:'/admin/sport/monitoring',title:'Monitoring',desc:'Hooper, RPE Foster, douleurs, GPS et accès au dossier longitudinal de chaque joueur.'},
  {href:'/admin/sport/comparator',title:'Comparateur',desc:'Comparer jusqu’à 4 profils athlétiques avec lecture descriptive et protocoles cohérents.'},
 ];
 return <main style={S.main}><header style={S.header}><div><span style={S.kicker}>PERFORMANCE · OPERATIONS</span><h1 style={S.h1}>Sport & Performance</h1><p style={S.p}>Séances, tests, GPS, alertes, monitoring et analyse. Chaque module garde sa propre identité tout en restant dans le même moteur.</p></div><a href='/admin' style={S.back}>← Portail</a></header><section style={S.grid}>{cards.map(c=><a key={c.title} href={c.href} style={S.card}><span style={S.badge}>PERFORMANCE</span><h2>{c.title}</h2><p>{c.desc}</p><b>Ouvrir →</b></a>)}</section><section style={S.split}><div><h2>Décision assistée</h2><p>Les alertes automatiques servent à déclencher une revue staff. Elles ne posent pas de diagnostic et n’excluent jamais automatiquement un joueur.</p></div><a href='/admin/administration' style={S.admin}>Accéder à Administration →</a></section></main>
}
const S:Record<string,React.CSSProperties>={main:{minHeight:'100vh',background:'transparent',color:'#FAFAFA',fontFamily:'Inter,system-ui,sans-serif',padding:28},header:{maxWidth:1180,margin:'0 auto 24px',display:'flex',justifyContent:'space-between',gap:20,alignItems:'flex-start'},kicker:{fontSize:10,letterSpacing:1.65,fontWeight:950,color:'var(--page-accent,var(--brand-accent,#F4F4F5))'},h1:{fontSize:'clamp(40px,6vw,72px)',margin:'4px 0 8px',letterSpacing:-3},p:{color:'#A1A1AA',maxWidth:700,lineHeight:1.5},back:{color:'#fff',textDecoration:'none',border:'1px solid var(--brand-border,#2B2B31)',padding:'10px 12px',borderRadius:10,background:'rgba(255,255,255,.025)'},grid:{maxWidth:1180,margin:'0 auto',display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(250px,1fr))',gap:14},card:{background:'linear-gradient(145deg,rgba(20,20,22,.96),rgba(12,12,14,.96))',border:'1px solid var(--brand-border,#2B2B31)',borderRadius:18,padding:20,color:'#fff',textDecoration:'none',display:'grid',gap:10,boxShadow:'0 18px 45px rgba(0,0,0,.14)'},badge:{fontSize:9,fontWeight:950,letterSpacing:1.25,color:'var(--page-accent,var(--brand-accent,#F4F4F5))'},split:{maxWidth:1180,margin:'20px auto 0',background:'rgba(20,20,22,.88)',border:'1px solid var(--brand-border,#2B2B31)',borderRadius:18,padding:20,display:'flex',justifyContent:'space-between',gap:16,alignItems:'center',flexWrap:'wrap'},admin:{background:'var(--brand-accent,#F4F4F5)',color:'var(--brand-bg,#09090B)',textDecoration:'none',borderRadius:10,padding:'12px 16px',fontWeight:900}};
