'use client';

import { useEffect, useState } from 'react';
import { supabase } from '@/lib/supabase';
import { useOrg } from '@/lib/org-context';
import { notifyInvite } from '@/lib/invite-client';

type Row=Record<string,any>;
const ROLES=['organization_admin','module_admin','team_admin','prepa_physique','coach','staff_medical','viewer'];
const ROLE_LABEL:Record<string,string>={organization_admin:'Administrateur organisation',module_admin:'Administrateur module',team_admin:'Administrateur équipe',prepa_physique:'Préparateur physique',coach:'Coach',staff_medical:'Staff médical',viewer:'Lecture seule'};
const PERMS=['manage_players','manage_monitoring','manage_tests','manage_teams','manage_users','manage_exports','all_settings'];

export default function StaffAccess(){
 const {environments,currentEnvId:org,setCurrentEnvId:setOrg,teamsFor,usesTeams}=useOrg();
 const [ready,setReady]=useState(false),[ok,setOk]=useState(false),[members,setMembers]=useState<Row[]>([]),[profiles,setProfiles]=useState<Row[]>([]),[msg,setMsg]=useState('');
 const [inviteName,setInviteName]=useState(''),[inviteEmail,setInviteEmail]=useState(''),[inviteRole,setInviteRole]=useState('prepa_physique'),[inviteTeam,setInviteTeam]=useState(''),[inviteLink,setInviteLink]=useState(''),[creating,setCreating]=useState(false);
 async function load(){const [m,p]=await Promise.all([supabase.from('memberships').select('*'),supabase.from('profiles').select('user_id,full_name,is_super_admin')]);setMembers(m.data||[]);setProfiles(p.data||[])}
 useEffect(()=>{(async()=>{const {data:{session}}=await supabase.auth.getSession();if(!session){setReady(true);return}const {data}=await supabase.from('profiles').select('is_super_admin').eq('user_id',session.user.id).maybeSingle();if(!data?.is_super_admin){setReady(true);return}setOk(true);await load();setReady(true)})()},[]);
 async function patch(id:string,patch:Row){const {error}=await supabase.from('memberships').update(patch).eq('id',id);setMsg(error?error.message:'Droits enregistrés ✓');if(!error)await load()}
 async function createInvite(e:React.FormEvent){e.preventDefault();setMsg('');setInviteLink('');if(!org){setMsg('Sélectionne un environnement.');return}setCreating(true);const {data,error}=await supabase.rpc('create_staff_invite',{p_organization_id:org,p_email:inviteEmail.trim(),p_full_name:inviteName.trim(),p_role:inviteRole,p_team_id:inviteTeam||null,p_expires_days:14});if(error){setCreating(false);setMsg(error.message);return}const row=Array.isArray(data)?data[0]:data;if(!row?.token){setCreating(false);setMsg('Invitation créée mais token indisponible.');return}const to=inviteEmail.trim();const link=`${window.location.origin}/join/staff?token=${encodeURIComponent(row.token)}`;setInviteLink(link);const label=environments.find(x=>x.id===org)?.branding?.label||environments.find(x=>x.id===org)?.name;const r=await notifyInvite({kind:'staff',inviteId:row.invite_id,token:row.token,email:to,name:inviteName.trim(),orgId:org,orgLabel:label});setCreating(false);if(r.status==='sent'){setMsg(`Invitation envoyée à ${to} ✓`);setInviteName('');setInviteEmail('')}else if(r.status==='manual')setMsg('Lien créé — à transmettre au membre (e-mail non configuré).');else setMsg(`Lien créé. Envoi e-mail échoué : ${r.message}`)}
 async function copyInvite(){if(!inviteLink)return;await navigator.clipboard.writeText(inviteLink);setMsg('Lien copié ✓')}
 if(!ready)return <main style={S.center}>Chargement…</main>;if(!ok)return <main style={S.center}>Accès administrateur principal requis.</main>;
 return <main style={S.main}><header style={S.headerLite}><a href='/admin/administration' style={S.back}>← Administration</a></header><section style={S.toolbar}><label>Environnement<select value={org} onChange={e=>setOrg(e.target.value)} style={S.input}>{environments.map(e=><option key={e.id} value={e.id}>{e.branding?.label||e.name}</option>)}</select></label></section>
 <section style={S.invite}><div><span style={S.kicker}>INVITATION SÉCURISÉE</span><h2>Ajouter un membre du staff</h2><p style={S.muted}>Le lien d’activation est nominatif et valable 14 jours. Les permissions fines se règlent ensuite ci-dessous.</p></div><form onSubmit={createInvite} style={S.inviteForm}><label>Nom complet<input style={S.input} value={inviteName} onChange={e=>setInviteName(e.target.value)} required/></label><label>E-mail<input style={S.input} type='email' value={inviteEmail} onChange={e=>setInviteEmail(e.target.value)} required/></label><label>Rôle<select style={S.input} value={inviteRole} onChange={e=>setInviteRole(e.target.value)}>{ROLES.map(r=><option key={r} value={r}>{ROLE_LABEL[r]}</option>)}</select></label>{usesTeams(org)&&<label>Équipe<select style={S.input} value={inviteTeam} onChange={e=>setInviteTeam(e.target.value)}><option value=''>Toutes équipes</option>{teamsFor(org).map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label>}<button style={S.button} disabled={creating}>{creating?'Création…':'Créer l’invitation'}</button></form>{inviteLink&&<div style={S.linkBox}><small>LIEN D’ACTIVATION · VALABLE 14 JOURS</small><code>{inviteLink}</code><button style={S.ghost} onClick={copyInvite}>Copier le lien</button></div>}</section>
 {msg&&<div style={S.notice}>{msg}</div>}<section style={S.grid}>{members.filter(m=>m.organization_id===org).map(m=>{const name=profiles.find(p=>p.user_id===m.user_id)?.full_name||m.user_id;const perms=m.permissions||{};return <article key={m.id} style={S.card}><div><b>{name}</b><small style={S.memberSub}>{teamsFor(org).find(t=>t.id===m.team_id)?.name||'Toutes équipes'}</small></div><label>Rôle<select value={m.role||'viewer'} onChange={e=>patch(m.id,{role:e.target.value})} style={S.input}>{ROLES.map(r=><option key={r} value={r}>{ROLE_LABEL[r]}</option>)}</select></label><div style={S.perms}>{PERMS.map(p=><label key={p}><input type='checkbox' checked={!!perms[p]} onChange={e=>patch(m.id,{permissions:{...perms,[p]:e.target.checked}})}/>{p}</label>)}</div><label><input type='checkbox' checked={!!m.medical_clearance} onChange={e=>patch(m.id,{medical_clearance:e.target.checked})}/> Accès médical détaillé</label><label><input type='checkbox' checked={m.active!==false} onChange={e=>patch(m.id,{active:e.target.checked})}/> Compte actif</label></article>})}</section></main>
}
const S:Record<string,React.CSSProperties>={center:{minHeight:'80vh',display:'grid',placeItems:'center'},main:{minHeight:'100vh',background:'#09090B',color:'#FAFAFA',fontFamily:'Inter,system-ui,sans-serif',padding:28},headerLite:{maxWidth:1200,margin:'0 auto 18px',display:'flex',justifyContent:'flex-end'},header:{maxWidth:1200,margin:'0 auto 20px',display:'flex',justifyContent:'space-between',gap:20,flexWrap:'wrap'},kicker:{fontSize:11,fontWeight:900,letterSpacing:1.4,color:'#E31E24'},back:{color:'#fff',textDecoration:'none',border:'1px solid #2B2B31',padding:'10px 12px',borderRadius:10,height:'fit-content'},toolbar:{maxWidth:1200,margin:'0 auto 16px',background:'#141416',border:'1px solid #2B2B31',borderRadius:16,padding:14},input:{width:'100%',height:42,background:'#1B1B1F',color:'#fff',border:'1px solid #2B2B31',borderRadius:10,padding:'0 10px',marginTop:6,boxSizing:'border-box'},notice:{maxWidth:1200,margin:'0 auto 14px',background:'#141416',border:'1px solid #2B2B31',borderRadius:12,padding:12},invite:{maxWidth:1200,margin:'0 auto 16px',background:'#111113',border:'1px solid #2B2B31',borderRadius:18,padding:18,display:'grid',gap:14},inviteForm:{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(190px,1fr))',gap:10,alignItems:'end'},button:{height:42,border:0,borderRadius:10,background:'#E31E24',color:'#fff',fontWeight:900,padding:'0 14px'},ghost:{height:38,border:'1px solid #3F3F46',borderRadius:9,background:'#1A1A1D',color:'#fff',fontWeight:800,padding:'0 12px'},linkBox:{display:'grid',gap:8,background:'#19191C',border:'1px solid #2B2B31',padding:12,borderRadius:12,overflow:'hidden'},muted:{color:'#A1A1AA'},grid:{maxWidth:1200,margin:'0 auto',display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(290px,1fr))',gap:12},card:{background:'#141416',border:'1px solid #2B2B31',borderRadius:16,padding:16,display:'grid',gap:12},perms:{display:'grid',gridTemplateColumns:'1fr 1fr',gap:7,fontSize:12},memberSub:{display:'block',color:'#A1A1AA',marginTop:5}};