'use client';

import { useEffect, useState } from 'react';
import { supabase } from '@/lib/supabase';

type Row=Record<string,any>;
const DIAMBARS='d3136b7f-ef28-43e8-af53-30fa6de70c62';
const ELITE='5454ad8f-8f2b-4812-9923-ab7d0b1f8748';
const TEAMS=[{id:'d9bb5390-94cb-461e-b2cd-a326da2cfa3d',name:'PRO A'},{id:'44f6976d-f5ef-4dcf-980f-ce3995e99877',name:'U19 · PRO B'},{id:'28b38b9f-3de0-419d-8275-b331a074b7f4',name:'U17'},{id:'e652df98-4653-416c-b794-3763e38a629d',name:'U15'}];
const ROLES=['organization_admin','direction','medical','performance','coach','recruitment','staff'];
const PERMS=['manage_players','manage_monitoring','manage_tests','manage_teams','manage_users','manage_exports','all_settings'];

export default function StaffAccess(){
 const [ready,setReady]=useState(false),[ok,setOk]=useState(false),[org,setOrg]=useState(DIAMBARS),[members,setMembers]=useState<Row[]>([]),[profiles,setProfiles]=useState<Row[]>([]),[msg,setMsg]=useState('');
 async function load(){const [m,p]=await Promise.all([supabase.from('memberships').select('*'),supabase.from('profiles').select('user_id,full_name,is_super_admin')]);setMembers(m.data||[]);setProfiles(p.data||[])}
 useEffect(()=>{(async()=>{const {data:{session}}=await supabase.auth.getSession();if(!session){setReady(true);return}const {data}=await supabase.from('profiles').select('is_super_admin').eq('user_id',session.user.id).maybeSingle();if(!data?.is_super_admin){setReady(true);return}setOk(true);await load();setReady(true)})()},[]);
 async function patch(id:string,patch:Row){const {error}=await supabase.from('memberships').update(patch).eq('id',id);setMsg(error?error.message:'Droits enregistrés ✓');if(!error)await load()}
 if(!ready)return <main style={S.center}>Chargement…</main>;if(!ok)return <main style={S.center}>Accès administrateur principal requis.</main>;
 return <main style={S.main}><header style={S.header}><div><span style={S.kicker}>ADMINISTRATION</span><h1>Staff & Accès</h1><p>Rôles, permissions, comptes actifs et accès médical. Aucun outil sportif dans cet espace.</p></div><a href='/admin/administration' style={S.back}>← Administration</a></header><section style={S.toolbar}><label>Organisation<select value={org} onChange={e=>setOrg(e.target.value)} style={S.input}><option value={DIAMBARS}>DIAMBARS FC</option><option value={ELITE}>HDY ELITE</option></select></label></section>{msg&&<div style={S.notice}>{msg}</div>}<section style={S.grid}>{members.filter(m=>m.organization_id===org).map(m=>{const name=profiles.find(p=>p.user_id===m.user_id)?.full_name||m.user_id;const perms=m.permissions||{};return <article key={m.id} style={S.card}><div><b>{name}</b><small>{TEAMS.find(t=>t.id===m.team_id)?.name||'Toutes équipes'}</small></div><label>Rôle<select value={m.role||'staff'} onChange={e=>patch(m.id,{role:e.target.value})} style={S.input}>{ROLES.map(r=><option key={r}>{r}</option>)}</select></label><div style={S.perms}>{PERMS.map(p=><label key={p}><input type='checkbox' checked={!!perms[p]} onChange={e=>patch(m.id,{permissions:{...perms,[p]:e.target.checked}})}/>{p}</label>)}</div><label><input type='checkbox' checked={!!m.medical_clearance} onChange={e=>patch(m.id,{medical_clearance:e.target.checked})}/> Accès médical détaillé</label><label><input type='checkbox' checked={m.active!==false} onChange={e=>patch(m.id,{active:e.target.checked})}/> Compte actif</label></article>})}</section></main>
}
const S:Record<string,React.CSSProperties>={center:{minHeight:'80vh',display:'grid',placeItems:'center'},main:{minHeight:'100vh',background:'#09090B',color:'#FAFAFA',fontFamily:'Inter,system-ui,sans-serif',padding:28},header:{maxWidth:1200,margin:'0 auto 20px',display:'flex',justifyContent:'space-between',gap:20},kicker:{fontSize:11,fontWeight:900,letterSpacing:1.4,color:'#E31E24'},back:{color:'#fff',textDecoration:'none',border:'1px solid #2B2B31',padding:'10px 12px',borderRadius:10,height:'fit-content'},toolbar:{maxWidth:1200,margin:'0 auto 16px',background:'#141416',border:'1px solid #2B2B31',borderRadius:16,padding:14},input:{width:'100%',height:42,background:'#1B1B1F',color:'#fff',border:'1px solid #2B2B31',borderRadius:10,padding:'0 10px',marginTop:6},notice:{maxWidth:1200,margin:'0 auto 14px',background:'#141416',border:'1px solid #2B2B31',borderRadius:12,padding:12},grid:{maxWidth:1200,margin:'0 auto',display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(290px,1fr))',gap:12},card:{background:'#141416',border:'1px solid #2B2B31',borderRadius:16,padding:16,display:'grid',gap:12},perms:{display:'grid',gridTemplateColumns:'1fr 1fr',gap:7,fontSize:12}};