'use client';

import { useEffect, useState } from 'react';
import { supabase } from '@/lib/supabase';

type Row=Record<string,any>;
const DIAMBARS='d3136b7f-ef28-43e8-af53-30fa6de70c62';
const ELITE='5454ad8f-8f2b-4812-9923-ab7d0b1f8748';
const TEAMS=[{id:'d9bb5390-94cb-461e-b2cd-a326da2cfa3d',name:'PRO A'},{id:'44f6976d-f5ef-4dcf-980f-ce3995e99877',name:'U19 · PRO B'},{id:'28b38b9f-3de0-419d-8275-b331a074b7f4',name:'U17'},{id:'e652df98-4653-416c-b794-3763e38a629d',name:'U15'}];
const ROLES=['organization_admin','module_admin','team_admin','prepa_physique','coach','staff_medical','viewer'];
const ROLE_LABEL:Record<string,string>={organization_admin:'Administrateur organisation',module_admin:'Administrateur module',team_admin:'Administrateur équipe',prepa_physique:'Préparateur physique',coach:'Coach',staff_medical:'Staff médical',viewer:'Lecture seule'};
const PERMS=['manage_players','manage_monitoring','manage_tests','manage_teams','manage_users','manage_exports','all_settings'];

export default function StaffAccess(){
 const [ready,setReady]=useState(false),[ok,setOk]=useState(false),[org,setOrg]=useState(DIAMBARS),[members,setMembers]=useState<Row[]>([]),[profiles,setProfiles]=useState<Row[]>([]),[msg,setMsg]=useState('');
 const [inviteName,setInviteName]=useState(''),[inviteEmail,setInviteEmail]=useState(''),[inviteTeam,setInviteTeam]=useState(''),[inviteLink,setInviteLink]=useState(''),[creating,setCreating]=useState(false);
 async function load(){const [m,p]=await Promise.all([supabase.from('memberships').select('*'),supabase.from('profiles').select('user_id,full_name,is_super_admin')]);setMembers(m.data||[]);setProfiles(p.data||[])}
 useEffect(()=>{(async()=>{const {data:{session}}=await supabase.auth.getSession();if(!session){setReady(true);return}const {data}=await supabase.from('profiles').select('is_super_admin').eq('user_id',session.user.id).maybeSingle();if(!data?.is_super_admin){setReady(true);return}setOk(true);await load();setReady(true)})()},[]);
 async function patch(id:string,patch:Row){const {error}=await supabase.from('memberships').update(patch).eq('id',id);setMsg(error?error.message:'Droits enregistrés ✓');if(!error)await load()}
 async function createPrepaInvite(e:React.FormEvent){e.preventDefault();setMsg('');setInviteLink('');if(org!==DIAMBARS){setMsg('Les invitations préparateurs de ce pilote sont limitées à Diambars FC.');return}setCreating(true);const {data,error}=await supabase.rpc('create_staff_invite',{p_organization_id:DIAMBARS,p_email:inviteEmail.trim(),p_full_name:inviteName.trim(),p_role:'prepa_physique',p_team_id:inviteTeam||null,p_expires_days:14});setCreating(false);if(error){setMsg(error.message);return}const row=Array.isArray(data)?data[0]:data;if(!row?.token){setMsg('Invitation créée mais token indisponible.');return}const link=`${window.location.origin}/join/staff?token=${encodeURIComponent(row.token)}`;setInviteLink(link);setMsg('Invitation préparateur physique créée ✓')}
 async function copyInvite(){if(!inviteLink)return;await navigator.clipboard.writeText(inviteLink);setMsg('Lien copié ✓')}
 if(!ready)return <main style={S.center}>Chargement…</main>;if(!ok)return <main style={S.center}>Accès administrateur principal requis.</main>;
 return <main style={S.main}><header style={S.headerLite}><a href='/admin/administration' style={S.back}>← Administration</a></header><section style={S.toolbar}><label>Organisation<select value={org} onChange={e=>setOrg(e.target.value)} style={S.input}><option value={DIAMBARS}>DIAMBARS FC</option><option value={ELITE}>HDY ELITE</option></select></label></section>
 {org===DIAMBARS&&<section style={S.invite}><div><span style={S.kicker}>INVITATION SÉCURISÉE</span><h2>Ajouter un préparateur physique</h2><p style={S.muted}>L’accès créé donne le rôle <b>prepa_physique</b>, sans accès médical détaillé ni gestion des utilisateurs.</p></div><form onSubmit={createPrepaInvite} style={S.inviteForm}><label>Nom complet<input style={S.input} value={inviteName} onChange={e=>setInviteName(e.target.value)} required/></label><label>E-mail<input style={S.input} type='email' value={inviteEmail} onChange={e=>setInviteEmail(e.target.value)} required/></label><label>Équipe<select style={S.input} value={inviteTeam} onChange={e=>setInviteTeam(e.target.value)}><option value=''>Toutes équipes</option>{TEAMS.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><button style={S.button} disabled={creating}>{creating?'Création…':'Créer l’invitation'}</button></form>{inviteLink&&<div style={S.linkBox}><small>LIEN D’ACTIVATION · VALABLE 14 JOURS</small><code>{inviteLink}</code><button style={S.ghost} onClick={copyInvite}>Copier le lien</button></div>}</section>}
 {msg&&<div style={S.notice}>{msg}</div>}<section style={S.grid}>{members.filter(m=>m.organization_id===org).map(m=>{const name=profiles.find(p=>p.user_id===m.user_id)?.full_name||m.user_id;const perms=m.permissions||{};return <article key={m.id} style={S.card}><div><b>{name}</b><small style={S.memberSub}>{TEAMS.find(t=>t.id===m.team_id)?.name||'Toutes équipes'}</small></div><label>Rôle<select value={m.role||'viewer'} onChange={e=>patch(m.id,{role:e.target.value})} style={S.input}>{ROLES.map(r=><option key={r} value={r}>{ROLE_LABEL[r]}</option>)}</select></label><div style={S.perms}>{PERMS.map(p=><label key={p}><input type='checkbox' checked={!!perms[p]} onChange={e=>patch(m.id,{permissions:{...perms,[p]:e.target.checked}})}/>{p}</label>)}</div><label><input type='checkbox' checked={!!m.medical_clearance} onChange={e=>patch(m.id,{medical_clearance:e.target.checked})}/> Accès médical détaillé</label><label><input type='checkbox' checked={m.active!==false} onChange={e=>patch(m.id,{active:e.target.checked})}/> Compte actif</label></article>})}</section></main>
}
const S:Record<string,React.CSSProperties>={center:{minHeight:'80vh',display:'grid',placeItems:'center'},main:{minHeight:'100vh',background:'#09090B',color:'#FAFAFA',fontFamily:'Inter,system-ui,sans-serif',padding:28},headerLite:{maxWidth:1200,margin:'0 auto 18px',display:'flex',justifyContent:'flex-end'},header:{maxWidth:1200,margin:'0 auto 20px',display:'flex',justifyContent:'space-between',gap:20,flexWrap:'wrap'},kicker:{fontSize:11,fontWeight:900,letterSpacing:1.4,color:'#E31E24'},back:{color:'#fff',textDecoration:'none',border:'1px solid #2B2B31',padding:'10px 12px',borderRadius:10,height:'fit-content'},toolbar:{maxWidth:1200,margin:'0 auto 16px',background:'#141416',border:'1px solid #2B2B31',borderRadius:16,padding:14},input:{width:'100%',height:42,background:'#1B1B1F',color:'#fff',border:'1px solid #2B2B31',borderRadius:10,padding:'0 10px',marginTop:6,boxSizing:'border-box'},notice:{maxWidth:1200,margin:'0 auto 14px',background:'#141416',border:'1px solid #2B2B31',borderRadius:12,padding:12},invite:{maxWidth:1200,margin:'0 auto 16px',background:'#111113',border:'1px solid #2B2B31',borderRadius:18,padding:18,display:'grid',gap:14},inviteForm:{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(190px,1fr))',gap:10,alignItems:'end'},button:{height:42,border:0,borderRadius:10,background:'#E31E24',color:'#fff',fontWeight:900,padding:'0 14px'},ghost:{height:38,border:'1px solid #3F3F46',borderRadius:9,background:'#1A1A1D',color:'#fff',fontWeight:800,padding:'0 12px'},linkBox:{display:'grid',gap:8,background:'#19191C',border:'1px solid #2B2B31',padding:12,borderRadius:12,overflow:'hidden'},muted:{color:'#A1A1AA'},grid:{maxWidth:1200,margin:'0 auto',display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(290px,1fr))',gap:12},card:{background:'#141416',border:'1px solid #2B2B31',borderRadius:16,padding:16,display:'grid',gap:12},perms:{display:'grid',gridTemplateColumns:'1fr 1fr',gap:7,fontSize:12},memberSub:{display:'block',color:'#A1A1AA',marginTop:5}};