'use client';

import { useEffect, useMemo, useState } from 'react';
import * as XLSX from 'xlsx';
import { supabase } from '@/lib/supabase';

type Row=Record<string,any>;
const DIAMBARS='d3136b7f-ef28-43e8-af53-30fa6de70c62';
const ELITE='5454ad8f-8f2b-4812-9923-ab7d0b1f8748';
const TEAMS=[{id:'d9bb5390-94cb-461e-b2cd-a326da2cfa3d',name:'PRO A'},{id:'44f6976d-f5ef-4dcf-980f-ce3995e99877',name:'U19 · PRO B'},{id:'28b38b9f-3de0-419d-8275-b331a074b7f4',name:'U17'},{id:'e652df98-4653-416c-b794-3763e38a629d',name:'U15'}];
const STEPS=['Identité','Sport','Famille','Scolarité','Historique clubs'];

// --- Import CSV joueurs (cahier des charges §2/§12, CA-01/CA-09) ---
function normKey(s:string){return String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]/g,'')}
function pickCol(r:Row,keys:string[]){for(const [h,v] of Object.entries(r)){if(keys.some(k=>normKey(k)===normKey(h)))return String(v??'').trim()}return ''}
function csvParse(text:string){const first=text.split(/\r?\n/)[0]||'';const sep=(first.match(/;/g)||[]).length>(first.match(/,/g)||[]).length?';':',';const lines=text.split(/\r?\n/).filter(x=>x.trim());if(lines.length<2)return [] as Row[];const split=(line:string)=>line.split(sep).map(x=>x.trim().replace(/^"|"$/g,''));const head=split(lines[0]);return lines.slice(1).map(line=>{const a=split(line);const r:Row={};head.forEach((h,i)=>r[h]=a[i]??'');return r})}
function isoDateLoose(v:string){if(!v)return '';const s=v.trim();let m=s.match(/^(\d{4})-(\d{2})-(\d{2})/);if(m)return `${m[1]}-${m[2]}-${m[3]}`;m=s.match(/^(\d{1,2})[\/\-](\d{1,2})[\/\-](\d{4})$/);if(m)return `${m[3]}-${String(m[2]).padStart(2,'0')}-${String(m[1]).padStart(2,'0')}`;return ''}
function matchTeam(label:string){const n=normKey(label);if(!n)return '';return TEAMS.find(t=>normKey(t.name)===n||normKey(t.name).includes(n)||n.includes(normKey(t.name)))?.id||''}

export default function Registration(){
 const [ready,setReady]=useState(false),[ok,setOk]=useState(false),[msg,setMsg]=useState(''),[step,setStep]=useState(0);
 const [org,setOrg]=useState(DIAMBARS),[team,setTeam]=useState(TEAMS[2].id);
 const [p,setP]=useState<Row>({first_name:'',last_name:'',preferred_name:'',sex:'',birth_date:'',birth_place:'',nationalities:'',license_number:'',languages:'',phone:'',email:'',address:'',city:'',country:'Sénégal',category:'U17',season:'2026-2027',jersey_number:'',primary_position:'',secondary_positions:'',dominant_foot:'',weak_foot_level:'',height_cm:'',weight_kg:'',wingspan_cm:'',club_arrival_date:'',contract_type:'',selections:'',agent_name:'',agent_phone:'',agent_email:''});
 const [g,setG]=useState<Row>({full_name:'',relationship:'',phone:'',email:'',address:'',city:'',country:'Sénégal',is_legal_representative:true,is_primary_contact:true,is_emergency_contact:true,lives_with_player:true,notes:''});
 const [e,setE]=useState<Row>({school_name:'',school_city:'',class_level:'',study_track:'',diploma_target:'',school_status:'',schedule_summary:'',constraints:'',school_referent_name:'',school_referent_phone:'',school_referent_email:'',academic_project:'',professional_project:'',notes:''});
 const [c,setC]=useState<Row>({club_name:'',country:'',city:'',competition_level:'',category:'',season:'',age_at_club:'',position:'',matches:'',starts:'',minutes_played:'',goals:'',assists:'',training_sessions_per_week:'',training_sessions_per_season:'',average_session_duration_min:'',strength_sessions_per_week:'',tournaments:'',selections:'',injuries_summary:'',start_date:'',end_date:'',notes:''});
 const [mode,setMode]=useState<'single'|'csv'>('single');
 const [csvRows,setCsvRows]=useState<Row[]>([]),[csvFile,setCsvFile]=useState(''),[csvMsg,setCsvMsg]=useState(''),[csvSaving,setCsvSaving]=useState(false),[csvDone,setCsvDone]=useState<{ok:number;dup:number}|null>(null);
 const isD=org===DIAMBARS; const theme=isD?{bg:'#09090B',surface:'#141416',surface2:'#1B1B1F',border:'#2B2B31',text:'#FAFAFA',muted:'#92929B',accent:'#E31E24'}:{bg:'#F4F4F5',surface:'#fff',surface2:'#F7F7F8',border:'#E4E4E7',text:'#111',muted:'#71717A',accent:'#111'};
 useEffect(()=>{(async()=>{const {data:{session}}=await supabase.auth.getSession();if(!session){setReady(true);return}const {data}=await supabase.from('profiles').select('is_super_admin').eq('user_id',session.user.id).maybeSingle();setOk(!!data?.is_super_admin);setReady(true)})()},[]);
 useEffect(()=>{if(org===ELITE)setTeam('');else if(!TEAMS.some(t=>t.id===team))setTeam(TEAMS[2].id)},[org,team]);
 function set<K extends 'p'|'g'|'e'|'c'>(which:K,key:string,value:any){const fn=which==='p'?setP:which==='g'?setG:which==='e'?setE:setC;fn((v:Row)=>({...v,[key]:value}))}
 async function save(){
  if(!p.first_name||!p.last_name){setMsg('Prénom et nom sont obligatoires.');setStep(0);return}
  setMsg('Création du dossier…');
  const payload={organization_id:org,team_id:team||null,first_name:p.first_name,last_name:p.last_name,display_name:`${p.first_name} ${p.last_name}`.trim(),preferred_name:n(p.preferred_name),sex:n(p.sex),birth_date:n(p.birth_date),birth_place:n(p.birth_place),nationalities:arr(p.nationalities),license_number:n(p.license_number),languages:arr(p.languages),phone:n(p.phone),email:n(p.email),address:n(p.address),city:n(p.city),country:n(p.country),category:n(p.category),season:n(p.season),jersey_number:num(p.jersey_number),primary_position:n(p.primary_position),secondary_positions:arr(p.secondary_positions),dominant_foot:n(p.dominant_foot),weak_foot_level:num(p.weak_foot_level),height_cm:num(p.height_cm),weight_kg:num(p.weight_kg),wingspan_cm:num(p.wingspan_cm),club_arrival_date:n(p.club_arrival_date),contract_type:n(p.contract_type),selections:n(p.selections),agent_name:n(p.agent_name),agent_phone:n(p.agent_phone),agent_email:n(p.agent_email),status:'disponible',dossier_status:'draft',active:true};
  const {data:player,error}=await supabase.from('players').insert(payload).select('id').single();
  if(error||!player){setMsg(error?.message||'Création impossible.');return}
  const jobs:PromiseLike<any>[]=[];
  if(g.full_name)jobs.push(supabase.from('player_guardians').insert({organization_id:org,player_id:player.id,full_name:g.full_name,relationship:n(g.relationship),phone:n(g.phone),email:n(g.email),address:n(g.address),city:n(g.city),country:n(g.country),is_legal_representative:!!g.is_legal_representative,is_primary_contact:!!g.is_primary_contact,is_emergency_contact:!!g.is_emergency_contact,lives_with_player:!!g.lives_with_player,notes:n(g.notes)}));
  if(e.school_name||e.class_level)jobs.push(supabase.from('player_education').insert({organization_id:org,player_id:player.id,...clean(e)}));
  if(c.club_name)jobs.push(supabase.from('player_club_history').insert({organization_id:org,player_id:player.id,club_name:c.club_name,country:n(c.country),city:n(c.city),competition_level:n(c.competition_level),category:n(c.category),season:n(c.season),age_at_club:num(c.age_at_club),position:n(c.position),matches:num(c.matches),starts:num(c.starts),minutes_played:num(c.minutes_played),goals:num(c.goals),assists:num(c.assists),training_sessions_per_week:num(c.training_sessions_per_week),training_sessions_per_season:num(c.training_sessions_per_season),average_session_duration_min:num(c.average_session_duration_min),strength_sessions_per_week:num(c.strength_sessions_per_week),tournaments:n(c.tournaments),selections:n(c.selections),injuries_summary:n(c.injuries_summary),start_date:n(c.start_date),end_date:n(c.end_date),notes:n(c.notes)}));
  const results=await Promise.all(jobs);const relatedError=results.find((x:any)=>x?.error)?.error;
  setMsg(relatedError?`Joueur créé, mais un sous-dossier a échoué : ${relatedError.message}`:`Dossier de ${p.first_name} ${p.last_name} créé ✓`);
  if(!relatedError)setTimeout(()=>location.href='/admin/administration',700);
 }
 const csvPreview=useMemo(()=>csvRows.map(r=>{const first_name=pickCol(r,['prenom','prénom','first name','firstname']);const last_name=pickCol(r,['nom','last name','lastname','nom de famille']);const email=pickCol(r,['email','e-mail','mail']);const birth_date=isoDateLoose(pickCol(r,['naissance','date de naissance','birth date','birthdate','dob']));const categoryLabel=pickCol(r,['categorie','catégorie','equipe','équipe','category','team']);const position=pickCol(r,['poste','position']);const team_id=isD?matchTeam(categoryLabel):'';return {first_name,last_name,email,birth_date,categoryLabel,position,team_id,valid:!!(first_name&&last_name&&email)}}),[csvRows,isD]);
 async function loadCsvFile(f:File){setCsvMsg('');setCsvFile(f.name);setCsvDone(null);if(/\.xlsx?$/i.test(f.name)){const ab=await f.arrayBuffer();const wb=XLSX.read(ab,{type:'array'});const sheet=wb.Sheets[wb.SheetNames[0]];const parsed=XLSX.utils.sheet_to_json<Record<string,unknown>>(sheet,{defval:''}).map(o=>Object.fromEntries(Object.entries(o).map(([k,v])=>[k,String(v??'')])) as Row);setCsvRows(parsed);if(!parsed.length)setCsvMsg('Aucune ligne détectée dans le fichier.');return}const parsed=csvParse(await f.text());setCsvRows(parsed);if(!parsed.length)setCsvMsg('CSV vide ou format non reconnu.')}
 async function saveCsv(){const valid=csvPreview.filter(x=>x.valid);if(!valid.length){setCsvMsg('Aucune ligne exploitable (prénom, nom et email sont obligatoires).');return}setCsvSaving(true);setCsvMsg('');const emails=valid.map(x=>x.email.toLowerCase());const {data:existing}=await supabase.from('players').select('email').eq('organization_id',org).in('email',emails);const existingSet=new Set((existing||[]).map((x:any)=>String(x.email||'').toLowerCase()));const toInsert=valid.filter(x=>!existingSet.has(x.email.toLowerCase()));const dup=valid.length-toInsert.length;if(!toInsert.length){setCsvSaving(false);setCsvMsg(`${dup} ligne(s) déjà présente(s) (email existant) — aucun doublon ajouté.`);return}const payload=toInsert.map(x=>({organization_id:org,team_id:x.team_id||null,first_name:x.first_name,last_name:x.last_name,display_name:`${x.first_name} ${x.last_name}`.trim(),email:x.email||null,birth_date:x.birth_date||null,category:x.categoryLabel||null,primary_position:x.position||null,status:'disponible',dossier_status:'draft',active:true}));const {error}=await supabase.from('players').insert(payload);setCsvSaving(false);if(error){setCsvMsg(`Import échoué : ${error.message}`);return}setCsvDone({ok:toInsert.length,dup});setCsvMsg(`${toInsert.length} joueur(s) importé(s)${dup?` · ${dup} doublon(s) ignoré(s) (email déjà existant)`:''}.`);setCsvRows([])}
 if(!ready)return <main style={S.center}>Chargement…</main>; if(!ok)return <main style={S.center}>Accès administrateur principal requis.</main>;
 return <main style={{minHeight:'100vh',background:theme.bg,color:theme.text,fontFamily:'Inter,system-ui,sans-serif'}}><header style={{...S.header,background:theme.surface,borderColor:theme.border}}><a href='/admin/administration' style={{...S.back,color:theme.text,borderColor:theme.border}}>← Administration</a><div><b>INSCRIPTION JOUEUR</b><small style={{display:'block',color:theme.muted}}>Création du dossier longitudinal</small></div></header><section style={S.wrap}>
 <div style={{...S.switcher,background:theme.surface,borderColor:theme.border}}><label>ORGANISATION<select value={org} onChange={x=>setOrg(x.target.value)} style={field(theme)}><option value={DIAMBARS}>DIAMBARS FC</option><option value={ELITE}>HDY ELITE</option></select></label>{isD&&mode==='single'&&<label>ÉQUIPE<select value={team} onChange={x=>setTeam(x.target.value)} style={field(theme)}>{TEAMS.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label>}</div>
 <div style={{...S.mode,borderColor:theme.border}}><button onClick={()=>setMode('single')} style={{...S.modeBtn,background:mode==='single'?theme.accent:'transparent',color:mode==='single'?'#fff':theme.text}}>Un joueur</button><button onClick={()=>setMode('csv')} style={{...S.modeBtn,background:mode==='csv'?theme.accent:'transparent',color:mode==='csv'?'#fff':theme.text}}>Import CSV</button></div>
 {mode==='single'?<>
 <nav style={{...S.steps,background:theme.surface,borderColor:theme.border}}>{STEPS.map((x,i)=><button key={x} onClick={()=>setStep(i)} style={{...S.step,background:i===step?theme.accent:'transparent',color:i===step?'#fff':theme.muted}}>{i+1}. {x}</button>)}</nav>{msg&&<div style={{...S.notice,background:theme.surface,borderColor:theme.border}}>{msg}</div>}
 <section style={{...S.card,background:theme.surface,borderColor:theme.border}}>
 {step===0&&<><h1>Informations personnelles</h1><p style={{color:theme.muted}}>Identité, coordonnées et informations administratives du joueur.</p><Grid fields={PERSONAL} data={p} setData={(k,v)=>set('p',k,v)} theme={theme}/></>}
 {step===1&&<><h1>Informations sportives</h1><p style={{color:theme.muted}}>Profil football à l’entrée dans la structure.</p><Grid fields={SPORT} data={p} setData={(k,v)=>set('p',k,v)} theme={theme}/></>}
 {step===2&&<><h1>Famille & urgence</h1><p style={{color:theme.muted}}>Représentant légal, contact principal et urgence.</p><Grid fields={FAMILY} data={g} setData={(k,v)=>set('g',k,v)} theme={theme}/><div style={S.checks}>{[['is_legal_representative','Représentant légal'],['is_primary_contact','Contact principal'],['is_emergency_contact','Contact urgence'],['lives_with_player','Vit avec le joueur']].map(([k,l])=><label key={k}><input type='checkbox' checked={!!g[k]} onChange={x=>set('g',k,x.target.checked)}/>{l}</label>)}</div></>}
 {step===3&&<><h1>Scolarité & projet</h1><p style={{color:theme.muted}}>École, niveau, contraintes, projet académique et professionnel.</p><Grid fields={EDU} data={e} setData={(k,v)=>set('e',k,v)} theme={theme}/></>}
 {step===4&&<><h1>Historique clubs</h1><p style={{color:theme.muted}}>Expérience sportive avant l’arrivée : clubs, volume, matchs, entraînement et blessures déclarées.</p><Grid fields={CLUB} data={c} setData={(k,v)=>set('c',k,v)} theme={theme}/></>}
 <div style={S.actions}><button disabled={step===0} onClick={()=>setStep(Math.max(0,step-1))} style={{...S.secondary,color:theme.text,borderColor:theme.border}}>Précédent</button>{step<4?<button onClick={()=>setStep(step+1)} style={{...S.primary,background:theme.accent}}>Continuer</button>:<button onClick={save} style={{...S.primary,background:theme.accent}}>Créer le dossier joueur</button>}</div>
 </section></>:<section style={{...S.card,background:theme.surface,borderColor:theme.border}}>
 <h1>Import CSV / Excel</h1><p style={{color:theme.muted}}>Colonnes attendues : prénom, nom, email, date de naissance, catégorie (ex. U15/U17/PRO), poste. Prénom, nom et email sont obligatoires ; les emails déjà présents dans l’organisation sont ignorés automatiquement pour éviter les doublons.</p>
 <input type='file' accept='.csv,.xlsx,.xls,text/csv,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' onChange={x=>x.target.files?.[0]&&loadCsvFile(x.target.files[0])} style={{display:'block',margin:'14px 0',color:theme.text}}/>
 {csvMsg&&<p style={{...S.notice,background:theme.surface2,borderColor:theme.border,color:theme.text}}>{csvMsg}</p>}
 {csvRows.length>0&&<>
 <div style={{margin:'10px 0',color:theme.muted}}>{csvFile} · <b>{csvRows.length}</b> ligne(s) lues · <b>{csvPreview.filter(x=>x.valid).length}</b> exploitable(s)</div>
 <div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse',fontSize:13}}><thead><tr>{['Prénom','Nom','Email','Naissance','Catégorie','Équipe détectée','Poste',''].map(h=><th key={h} style={{textAlign:'left',padding:'6px 8px',borderBottom:`1px solid ${theme.border}`,color:theme.muted}}>{h}</th>)}</tr></thead><tbody>{csvPreview.slice(0,200).map((x,i)=><tr key={i}>{[x.first_name,x.last_name,x.email,x.birth_date||'—',x.categoryLabel||'—',isD?(TEAMS.find(t=>t.id===x.team_id)?.name||'non reconnue'):'—',x.position||'—'].map((v,j)=><td key={j} style={{padding:'6px 8px',borderBottom:`1px solid ${theme.border}`}}>{v}</td>)}<td style={{padding:'6px 8px',borderBottom:`1px solid ${theme.border}`,fontWeight:800,color:x.valid?'#16A34A':'#DC2626'}}>{x.valid?'OK':'incomplet'}</td></tr>)}</tbody></table></div>
 <button onClick={saveCsv} disabled={csvSaving||!csvPreview.some(x=>x.valid)} style={{...S.primary,background:theme.accent,marginTop:14}}>{csvSaving?'Import en cours…':`Importer ${csvPreview.filter(x=>x.valid).length} joueur(s)`}</button>
 </>}
 {csvDone&&<p style={{...S.notice,background:theme.surface2,borderColor:theme.border,color:theme.text,marginTop:12}}>Import terminé : <b>{csvDone.ok}</b> créé(s){csvDone.dup?<>, <b>{csvDone.dup}</b> doublon(s) ignoré(s)</>:null}. Complète les dossiers depuis <a href='/admin/roster' style={{color:theme.accent}}>l’effectif</a>.</p>}
 </section>}
 </section></main>
}

type Field=[string,string,string];
const PERSONAL:Field[]=[['first_name','Prénom','text'],['last_name','Nom','text'],['preferred_name','Nom usuel','text'],['sex','Sexe','text'],['birth_date','Date de naissance','date'],['birth_place','Lieu de naissance','text'],['nationalities','Nationalité(s)','text'],['license_number','N° licence','text'],['languages','Langues','text'],['phone','Téléphone','tel'],['email','Email','email'],['address','Adresse','text'],['city','Ville','text'],['country','Pays','text']];
const SPORT:Field[]=[['category','Catégorie','text'],['season','Saison','text'],['jersey_number','N° maillot','number'],['primary_position','Poste principal','text'],['secondary_positions','Postes secondaires','text'],['dominant_foot','Pied dominant','text'],['weak_foot_level','Niveau pied faible','number'],['height_cm','Taille cm','number'],['weight_kg','Poids kg','number'],['wingspan_cm','Envergure cm','number'],['club_arrival_date','Date arrivée club','date'],['contract_type','Type de contrat','text'],['selections','Sélections','text'],['agent_name','Agent','text'],['agent_phone','Téléphone agent','tel'],['agent_email','Email agent','email']];
const FAMILY:Field[]=[['full_name','Nom complet','text'],['relationship','Lien avec le joueur','text'],['phone','Téléphone','tel'],['email','Email','email'],['address','Adresse','text'],['city','Ville','text'],['country','Pays','text'],['notes','Notes','text']];
const EDU:Field[]=[['school_name','Établissement','text'],['school_city','Ville école','text'],['class_level','Niveau / classe','text'],['study_track','Filière','text'],['diploma_target','Diplôme visé','text'],['school_status','Statut scolaire','text'],['schedule_summary','Emploi du temps / contraintes horaires','text'],['constraints','Contraintes scolaires','text'],['school_referent_name','Référent scolaire','text'],['school_referent_phone','Téléphone référent','tel'],['school_referent_email','Email référent','email'],['academic_project','Projet académique','text'],['professional_project','Projet professionnel','text'],['notes','Notes','text']];
const CLUB:Field[]=[['club_name','Ancien club','text'],['country','Pays','text'],['city','Ville','text'],['competition_level','Niveau compétition','text'],['category','Catégorie','text'],['season','Saison','text'],['age_at_club','Âge dans ce club','number'],['position','Poste','text'],['matches','Matchs / saison','number'],['starts','Titularisations','number'],['minutes_played','Minutes jouées','number'],['goals','Buts','number'],['assists','Passes décisives','number'],['training_sessions_per_week','Entraînements / semaine','number'],['training_sessions_per_season','Entraînements / saison','number'],['average_session_duration_min','Durée moyenne séance','number'],['strength_sessions_per_week','Musculation / semaine','number'],['tournaments','Tournois','text'],['selections','Sélections','text'],['injuries_summary','Antécédents blessures déclarés','text'],['start_date','Début','date'],['end_date','Fin','date'],['notes','Notes','text']];
function Grid({fields,data,setData,theme}:{fields:Field[];data:Row;setData:(k:string,v:any)=>void;theme:any}){return <div style={S.grid}>{fields.map(([k,l,t])=><label key={k}>{l}<input type={t} value={data[k]??''} onChange={x=>setData(k,x.target.value)} style={field(theme)}/></label>)}</div>}
function arr(v:any){return String(v||'').split(',').map(x=>x.trim()).filter(Boolean)} function n(v:any){return v===''||v===undefined?null:v} function num(v:any){return v===''||v===undefined?null:Number(v)} function clean(o:Row){const r:Row={};Object.entries(o).forEach(([k,v])=>r[k]=n(v));return r}
function field(t:any):React.CSSProperties{return {width:'100%',height:44,boxSizing:'border-box',marginTop:6,border:`1px solid ${t.border}`,borderRadius:10,padding:'0 11px',background:t.surface2,color:t.text}}
const S:Record<string,React.CSSProperties>={center:{minHeight:'80vh',display:'grid',placeItems:'center'},header:{height:70,borderBottom:'1px solid',padding:'0 22px',display:'flex',gap:18,alignItems:'center',position:'sticky',top:0,zIndex:20},back:{textDecoration:'none',border:'1px solid',borderRadius:10,padding:'8px 11px'},wrap:{maxWidth:1180,margin:'0 auto',padding:24},switcher:{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(220px,300px))',gap:12,border:'1px solid',borderRadius:16,padding:14},mode:{display:'flex',gap:8,border:'1px solid',borderRadius:12,padding:6,margin:'12px 0'},modeBtn:{border:0,borderRadius:8,padding:'9px 14px',fontWeight:800,cursor:'pointer'},steps:{display:'flex',gap:7,border:'1px solid',borderRadius:14,padding:7,margin:'16px 0',overflowX:'auto'},step:{border:0,borderRadius:10,padding:'11px 14px',fontWeight:800,whiteSpace:'nowrap',cursor:'pointer'},notice:{border:'1px solid',borderRadius:12,padding:12,marginBottom:14},card:{border:'1px solid',borderRadius:18,padding:20},grid:{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(210px,1fr))',gap:12,marginTop:18},checks:{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(180px,1fr))',gap:10,marginTop:18},actions:{display:'flex',justifyContent:'space-between',gap:10,marginTop:24},primary:{border:0,color:'#fff',borderRadius:10,padding:'12px 17px',fontWeight:850,cursor:'pointer'},secondary:{background:'transparent',border:'1px solid',borderRadius:10,padding:'12px 17px',fontWeight:800,cursor:'pointer'}};