'use client';

export default function Administration(){
 const cards=[
  {href:'/admin/registration',title:'Inscription joueur',desc:'Créer le dossier administratif complet : identité, famille, scolarité, historique clubs.'},
  {href:'/admin/organizations',title:'Organisations & équipes',desc:'Gérer DIAMBARS FC, HDY ELITE et les périmètres d’équipes.'},
  {href:'/admin/administration/staff',title:'Staff & accès',desc:'Rôles, permissions, comptes actifs et accès médical.'},
 ];
 return <main style={S.main}><header style={S.header}><div><span style={S.kicker}>HDY PERFORMANCE ENGINE</span><h1 style={S.h1}>Administration</h1><p style={S.p}>Comptes, inscriptions, organisations et droits. Les opérations sportives sont séparées.</p></div><a href='/admin' style={S.back}>← Portail</a></header><section style={S.grid}>{cards.map(c=><a key={c.href} href={c.href} style={S.card}><span style={S.badge}>ADMIN</span><h2>{c.title}</h2><p>{c.desc}</p><b>Ouvrir →</b></a>)}</section><section style={S.split}><div><h2>Administration</h2><p>Création et mise à jour des dossiers, comptes et permissions.</p></div><a href='/admin/sport' style={S.sport}>Accéder à Sport & Performance →</a></section></main>
}
const S:Record<string,React.CSSProperties>={main:{minHeight:'100vh',background:'#09090B',color:'#FAFAFA',fontFamily:'Inter,system-ui,sans-serif',padding:28},header:{maxWidth:1180,margin:'0 auto 24px',display:'flex',justifyContent:'space-between',gap:20,alignItems:'flex-start'},kicker:{fontSize:11,letterSpacing:1.5,fontWeight:900,color:'#E31E24'},h1:{fontSize:'clamp(40px,6vw,72px)',margin:'4px 0 8px',letterSpacing:-3},p:{color:'#A1A1AA',maxWidth:650},back:{color:'#fff',textDecoration:'none',border:'1px solid #2B2B31',padding:'10px 12px',borderRadius:10},grid:{maxWidth:1180,margin:'0 auto',display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(250px,1fr))',gap:14},card:{background:'#141416',border:'1px solid #2B2B31',borderRadius:18,padding:20,color:'#fff',textDecoration:'none',display:'grid',gap:10},badge:{fontSize:10,fontWeight:900,color:'#E31E24'},split:{maxWidth:1180,margin:'20px auto 0',background:'#141416',border:'1px solid #2B2B31',borderRadius:18,padding:20,display:'flex',justifyContent:'space-between',gap:16,alignItems:'center',flexWrap:'wrap'},sport:{background:'#E31E24',color:'#fff',textDecoration:'none',borderRadius:10,padding:'12px 16px',fontWeight:850}};