'use client';

export default function Administration(){
 const cards=[
  {href:'/admin/registration',title:'Inscription joueur',desc:'Créer le dossier administratif complet : identité, famille, scolarité, historique clubs.'},
  {href:'/admin/organizations',title:'Organisations & équipes',desc:'Gérer DIAMBARS FC, HDY ELITE et les périmètres d’équipes.'},
  {href:'/admin/administration/staff',title:'Staff & accès',desc:'Rôles, permissions, comptes actifs et accès par environnement.'},
 ];
 return <main style={S.main}><header style={S.headerLite}><a href='/admin' style={S.back}>← Portail</a></header><section style={S.grid}>{cards.map(c=><a key={c.href} href={c.href} style={S.card}><span style={S.badge}>ADMIN</span><h2>{c.title}</h2><p>{c.desc}</p><b>Ouvrir →</b></a>)}</section><section style={S.split}><div><h2>Centre de contrôle</h2><p>Créer et mettre à jour les dossiers, comptes, organisations, rôles et permissions.</p></div><a href='/admin/sport' style={S.sport}>Accéder à Sport & Performance →</a></section></main>
}
const S:Record<string,React.CSSProperties>={main:{minHeight:'100vh',background:'transparent',color:'#FAFAFA',fontFamily:'Inter,system-ui,sans-serif',padding:28},headerLite:{maxWidth:1180,margin:'0 auto 18px',display:'flex',justifyContent:'flex-end'},header:{maxWidth:1180,margin:'0 auto 24px',display:'flex',justifyContent:'space-between',gap:20,alignItems:'flex-start'},kicker:{fontSize:10,letterSpacing:1.65,fontWeight:950,color:'var(--page-accent,var(--brand-accent,#F4F4F5))'},h1:{fontSize:'clamp(40px,6vw,72px)',margin:'4px 0 8px',letterSpacing:-3},p:{color:'#A1A1AA',maxWidth:650,lineHeight:1.5},back:{color:'#fff',textDecoration:'none',border:'1px solid var(--brand-border,#2B2B31)',padding:'10px 12px',borderRadius:10,background:'rgba(255,255,255,.025)'},grid:{maxWidth:1180,margin:'0 auto',display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(250px,1fr))',gap:14},card:{background:'linear-gradient(145deg,rgba(20,20,22,.96),rgba(12,12,14,.96))',border:'1px solid var(--brand-border,#2B2B31)',borderRadius:18,padding:20,color:'#fff',textDecoration:'none',display:'grid',gap:10,boxShadow:'0 18px 45px rgba(0,0,0,.14)'},badge:{fontSize:9,fontWeight:950,letterSpacing:1.25,color:'var(--page-accent,var(--brand-accent,#F4F4F5))'},split:{maxWidth:1180,margin:'20px auto 0',background:'rgba(20,20,22,.88)',border:'1px solid var(--brand-border,#2B2B31)',borderRadius:18,padding:20,display:'flex',justifyContent:'space-between',gap:16,alignItems:'center',flexWrap:'wrap'},sport:{background:'var(--brand-accent,#F4F4F5)',color:'var(--brand-bg,#09090B)',textDecoration:'none',borderRadius:10,padding:'12px 16px',fontWeight:900}};
