'use client';

import { useEffect, useMemo, useState } from 'react';
import { supabase } from '@/lib/supabase';
import { useOrg } from '@/lib/org-context';

type Row=Record<string,any>;
export default function TestsPage(){
 const {environments,currentEnvId:org,setCurrentEnvId:setOrg,currentTeamId:team,setCurrentTeamId:setTeam,teamsFor,usesTeams}=useOrg();
 const [ready,setReady]=useState(false),[ok,setOk]=useState(false),[players,setPlayers]=useState<Row[]>([]),[defs,setDefs]=useState<Row[]>([]),[results,setResults]=useState<Row[]>([]),[playerId,setPlayerId]=useState(''),[defId,setDefId]=useState(''),[trials,setTrials]=useState(''),[device,setDevice]=useState(''),[testedAt,setTestedAt]=useState(new Date().toISOString().slice(0,16)),[msg,setMsg]=useState('');
 async function load(){const [p,d,r]=await Promise.all([supabase.from('players').select('*').eq('active',true),supabase.from('test_definitions').select('*').eq('active',true),supabase.from('test_results').select('*').order('tested_at',{ascending:false}).limit(200)]);setPlayers(p.data||[]);setDefs(d.data||[]);setResults(r.data||[])}
 useEffect(()=>{(async()=>{const {data:{session}}=await supabase.auth.getSession();if(!session){setReady(true);return}const {data}=await supabase.from('profiles').select('is_super_admin').eq('user_id',session.user.id).maybeSingle();if(!data?.is_super_admin){setReady(true);return}setOk(true);await load();setReady(true)})()},[]);
 const scoped=useMemo(()=>players.filter(p=>p.organization_id===org&&(!usesTeams(org)||!team||p.team_id===team)),[players,org,team,usesTeams]);const visibleDefs=defs.filter(d=>d.organization_id===org||d.organization_id===null);
 useEffect(()=>{if(!scoped.some(p=>p.id===playerId))setPlayerId(scoped[0]?.id||'')},[scoped,playerId]);useEffect(()=>{if(!visibleDefs.some(d=>d.id===defId))setDefId(visibleDefs[0]?.id||'')},[visibleDefs,defId]);
 async function save(){const def=defs.find(d=>d.id===defId);const vals=trials.split(',').map(v=>Number(v.trim())).filter(Number.isFinite);if(!playerId||!def||!vals.length){setMsg('Sélectionne un joueur, un test et au moins une valeur.');return}const best=def.best_rule==='min'?Math.min(...vals):Math.max(...vals);const mean=vals.reduce((a,b)=>a+b,0)/vals.length;const {data:{session}}=await supabase.auth.getSession();const {error}=await supabase.from('test_results').insert({organization_id:org,test_definition_id:def.id,player_id:playerId,tested_at:new Date(testedAt).toISOString(),trials:vals,best_value:best,mean_value:mean,device:device||null,evaluator_user_id:session?.user.id||null,context:{protocol:def.protocol,unit:def.unit}});setMsg(error?error.message:`${def.name} enregistré : ${best} ${def.unit} ✓`);if(!error){setTrials('');setDevice('');await load()}}
 if(!ready)return <main style={S.center}>Chargement…</main>;if(!ok)return <main style={S.center}>Accès administrateur principal requis.</main>;
 return <main style={S.main}><header style={S.header}><div><span style={S.kicker}>SPORT & PERFORMANCE</span><h1>Tests & évaluations</h1><p>Saisie, protocoles et résultats. Aucun réglage administratif dans cet espace.</p></div><a href='/admin/sport' style={S.back}>← Sport & Performance</a></header><section style={S.toolbar}><label>Environnement<select value={org} onChange={e=>setOrg(e.target.value)} style={S.input}>{environments.map(e=><option key={e.id} value={e.id}>{e.branding?.label||e.name}</option>)}</select></label>{usesTeams(org)&&<label>Équipe<select value={team} onChange={e=>setTeam(e.target.value)} style={S.input}><option value=''>Toutes les équipes</option>{teamsFor(org).map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label>}</section>{msg&&<div style={S.notice}>{msg}</div>}<section style={S.grid}><article style={S.card}><h2>Nouveau résultat</h2><label>Joueur<select value={playerId} onChange={e=>setPlayerId(e.target.value)} style={S.input}>{scoped.map(p=><option key={p.id} value={p.id}>{p.display_name||`${p.first_name} ${p.last_name}`}</option>)}</select></label><label>Test<select value={defId} onChange={e=>setDefId(e.target.value)} style={S.input}>{visibleDefs.map(d=><option key={d.id} value={d.id}>{d.name} · {d.unit}</option>)}</select></label>{defs.find(d=>d.id===defId)&&<div style={S.protocol}><b>Protocole</b><span>{defs.find(d=>d.id===defId)?.protocol}</span><small>{defs.find(d=>d.id===defId)?.trial_count} essai(s) · meilleure valeur = {defs.find(d=>d.id===defId)?.best_rule}</small></div>}<label>Essais<input value={trials} onChange={e=>setTrials(e.target.value)} placeholder='43.1, 44.0, 43.7' style={S.input}/></label><label>Dispositif<input value={device} onChange={e=>setDevice(e.target.value)} placeholder='VALD, My Jump Lab, cellules…' style={S.input}/></label><label>Date / heure<input type='datetime-local' value={testedAt} onChange={e=>setTestedAt(e.target.value)} style={S.input}/></label><button onClick={save} style={S.primary}>Enregistrer le test</button></article><article style={S.card}><h2>Derniers résultats</h2>{results.filter(r=>scoped.some(p=>p.id===r.player_id)).slice(0,25).map(r=>{const p=players.find(x=>x.id===r.player_id),d=defs.find(x=>x.id===r.test_definition_id);return <div key={r.id} style={S.row}><span><b>{p?.display_name||`${p?.first_name||''} ${p?.last_name||''}`}</b><small>{d?.name||'Test'}</small></span><strong>{r.best_value??r.mean_value??'—'} {d?.unit||''}</strong></div>})}</article></section></main>
}
const S:Record<string,React.CSSProperties>={center:{minHeight:'80vh',display:'grid',placeItems:'center'},main:{minHeight:'100vh',background:'#09090B',color:'#FAFAFA',fontFamily:'Inter,system-ui,sans-serif',padding:28},header:{maxWidth:1200,margin:'0 auto 20px',display:'flex',justifyContent:'space-between',gap:20},kicker:{fontSize:11,fontWeight:900,letterSpacing:1.4,color:'#E31E24'},back:{color:'#fff',textDecoration:'none',border:'1px solid #2B2B31',padding:'10px 12px',borderRadius:10,height:'fit-content'},toolbar:{maxWidth:1200,margin:'0 auto 16px',background:'#141416',border:'1px solid #2B2B31',borderRadius:16,padding:14,display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(220px,1fr))',gap:12},input:{width:'100%',height:42,background:'#1B1B1F',color:'#fff',border:'1px solid #2B2B31',borderRadius:10,padding:'0 10px',marginTop:6,boxSizing:'border-box'},notice:{maxWidth:1200,margin:'0 auto 14px',background:'#141416',border:'1px solid #2B2B31',borderRadius:12,padding:12},grid:{maxWidth:1200,margin:'0 auto',display:'grid',gridTemplateColumns:'minmax(280px,.9fr) minmax(0,1.1fr)',gap:14},card:{background:'#141416',border:'1px solid #2B2B31',borderRadius:16,padding:16,display:'grid',gap:12},protocol:{border:'1px solid #2B2B31',borderRadius:12,padding:12,display:'grid',gap:5},primary:{border:0,borderRadius:10,padding:'12px 15px',fontWeight:850,color:'#fff',background:'#E31E24',cursor:'pointer'},row:{display:'flex',justifyContent:'space-between',gap:10,padding:'10px 0',borderBottom:'1px solid #2B2B31'},};